### ISSUE TITLE
Background color deployment node is not set

### ISSUE THREAD

**Issue by msche** [structurizr/dsl#10]
I'm trying to give a tagged deployment node a specific color/icon. The definition of the deployment node is as follows:

```
hermesNode = deploymentNode "Hermes Instance" "Instance of Hermes" "Docker Container" "DOCKER" {
    deploymentNode "OpenJDK 11" "" "OpenJDK 11" "JAVA" {
        containerInstance hermes
    }
}
```

The definition of the tag is as follows:

```
            element "DOCKER" {
                icon images/docker.png
                background #007bff
            }
```

When i look at the generated image for the deployment the tagged deployment node has no color while the icon is there. 

<img width="247" alt="Screen Shot 2020-09-30 at 1 17 09 PM" src="https://user-images.githubusercontent.com/7935081/94678741-41ef3f80-031f-11eb-912f-15c1e6d03458.png">

**Comment by simonbrowndotje** [comment]
The `background` property has no effect for deployment nodes (it's always white). But you can set the `stroke` and `color` properties.

**Comment by UBessle** [comment]
Hi @simonbrowndotje , 

please include this information (only stroke and colore may be used as styling properties for deployment nodes) in your DSL language reference. Because this document still says, that background and shape are valid style properties for all elements.

Unfortunately i've wasted some time to find out, that it's not my fault and that i did try to use something that cannot work.

Yes, of course i could have been searching in the list of closed issue earlier, but if the reference documentation says, that something should be working and there is no open issue regarding this, ...

Cheers, Uwe

**Comment by simonbrowndotje** [comment]
> please include this information (only stroke and colore may be used as styling properties for deployment nodes) in your DSL language reference.

The thing to remember here is that the DSL is rendering tool independent, so there's nothing preventing other people making different tools that do respect `background` for deployment nodes, for example.

> Because this document still says, that background and shape are valid style properties for all elements.

It does?

> Unfortunately i've wasted some time to find out, that it's not my fault and that i did try to use something that cannot work.

I'm sorry that you wasted time. The [Structurizr - Notation](https://structurizr.com/help/notation) page (which is linked to from [DSL language reference - element style](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#element-style)) does actually have a note about this.

<img width="1194" alt="Screenshot 2023-02-03 at 17 21 42" src="https://user-images.githubusercontent.com/1009874/216667292-c6ba03fe-255b-4237-9f18-df40a6a68863.png">

Perhaps in the future, if something isn't working, feel free to raise an issue or post a message on the [Slack group](https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg).
