### ISSUE TITLE
Allow include|exclude for relationships to|from Tags

### ISSUE THREAD

**Issue by SaschaWeisenberger** [structurizr/dsl#104]
In my scenario I have a containerInstance deployed on an old System. It is planned to deploy it on a new System. I wanted to show this on my deployment view, so I added the new containerInstance to another deploymentNode and gave it a tag "Planned". In this view I wanted to exclude all relationships to this container, because it doesn't exist yet.
Is this possible? If not: can you add that feature?

**Comment by simonbrowndotje** [comment]
I'm not sure I fully understand what you're trying to achieve - can you provide an example DSL definition? Thanks.

**Comment by SaschaWeisenberger** [comment]
Sure! Here it is:

``` dsl
workspace "My Company" {
    !impliedRelationships true

    model {
            Logging = softwareSystem "Logging" "" "Inhouse" {
                RabbitMQLogging = container "Rabbit MQ for Logging" "" "" "Bus"
                ElasticSearchLogs = container "ElasticSearch" "" "" "Database"
                LogCollector = container "Log Collecor" "" "C#, Console" "Inhouse" {
                    this -> RabbitMQLogging "fetch log data" "Nuget/API"
                    this -> ElasticSearchLogs "writes log data" "Nuget/API"
                }
                KibanaLogs = container "Kibana" "" "" "Browser" {
                    this -> ElasticSearchLogs "show data"
                }
            }
        }

        deploymentEnvironment "Production" {
          deploymentNode "Old Vm" {
            containerInstance RabbitMQLogging "" "Legacy"
          }
          deploymentNode "New Vm" {
            containerInstance RabbitMQLogging "" "Planned"
          }
        }
    }

    views {
        styles {
            element "Planned" {
                opacity 50
                border dotted
            }
        }

        themes default
        deployment * "Production" {
            include *
            exclude * -> "Planned" // <-- Not working, The element "Planned" does not exist...
            autolayout
        }
    }
}
```

**Comment by simonbrowndotje** [comment]
That DSL has an additional `}` character that causes the parsing to fail, but once fixed (and with the `exclude` line comments out), the resulting diagram doesn't include any relationships. Could you provide an example that includes the relationships that you'd like to include?

**Comment by simonbrowndotje** [comment]
Thanks! Probably adding the following script to your DSL is the easiest way to exclude relationships to elements with the `Planned` tag:

```
!script groovy {
    view = workspace.views.getViewWithKey("Production-Deployment");
    workspace.model.relationships.findAll { it.getDestination().hasTag("Planned") }.each{ view.remove(it); };
}
```

It results in this diagram:

![image](https://user-images.githubusercontent.com/1009874/150551615-ed1cd610-8579-4060-9033-d75871ce954e.png)

**Comment by SaschaWeisenberger** [comment]
Awesome! Thank you very much!
I didn't recognize the scripting feature before 🙈 There is so much to explore before even thinking about additional functions ^^
I really love structurizr!
