### ISSUE TITLE
Relationship style - text size and bounding box size

### ISSUE THREAD

**Issue by bensojh1** [structurizr/dsl#107]
I've increased the font size for all the relationships in the model but in some cases the text describing the relationship now is broken up to fit in the space provided.

styles { 
relationship "Relationship" 
   fontsize 41 
}

![image](https://user-images.githubusercontent.com/94983684/152169210-e5abda88-7f1f-4548-a5af-dff5c5d6869d.png)

is there a means to increase the size of the area that is provided for the relationship text (descriptions)?

**Comment by simonbrowndotje** [comment]
Yes, you can use the `width` property on the relationship style. See the following for more details:

 - https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#relationship-style
 - https://structurizr.com/help/notation
