### ISSUE TITLE
Using the script environment to parse dsl

### ISSUE THREAD

**Issue by im-bpriestman** [structurizr/dsl#108]
As discussed in discussed in https://github.com/structurizr/dsl/issues/59, I'd like to be able to `!include` directories of dsl files.

I'm looking at using a `!script` or `!plugin` to do this. I can see how to interact with the file system and I can see how to manipulate the `workspace` but I can't see how to invoke the [includeParser](https://github.com/structurizr/dsl/blob/ff67bac5a0f3bae9c559fabb324d5f1a56849be2/src/main/java/com/structurizr/dsl/IncludeParser.java). 

Is this possible? Or am I barking up the wrong tree?

**Comment by simonbrowndotje** [comment]
`!include <directory>` has been added to the DSL, so I'm closing this issue
