### ISSUE TITLE
Include and exclude by tag

### ISSUE THREAD

**Issue by aidmax** [structurizr/dsl#11]
Hi there, 

is it possible to include and exclude objects by tag? I just want to separate some elements of a context diagram into grouped items and create additional diagrams. Documentation says we can include/exclude only by name and it looks a bit tedious if we have 2-3 or more groups.
Is there a better way?

views {
        systemContext System "SystemContext" "System Context diagram." {
            include *

            # exclude Grouped systems
            exclude System1 System2 System3

            # exclude Grouped relationships
            exclude rel_System1 rel_System2 rel_System3

            autoLayout
        }

        systemContext Grouped "Group1" "System Context diagram." {

            # include Grouped systems
            include System1 System2 System3

            # exclude relationship to Group
            exclude rel_to_Grouped
            autoLayout
        }

**Comment by simonbrowndotje** [comment]
If you're using the Structurizr web renderer, you could try using the filtered view functionality, which allows you to exclude elements/relationships via tags -> https://structurizr.com/help/filtered-views

**Comment by aidmax** [comment]
Thank you for prompt answer, I will try :)

**Comment by ambition-consulting** [comment]
It would be great to have a better way of filtering - tags, regex, etc
