### ISSUE TITLE
Excluding relationships with tags in a Deployment Diagram

### ISSUE THREAD

**Issue by grahamalama** [structurizr/dsl#113]
I'm trying to hide relationships with tags in a deployment diagram, and it doesn't seem to work the same as it does with a container diagram.

Here is the DSL file I'm working from.
```
workspace {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            mobileApp = container "Mobile App" "" "" "Mobile App"
            gateway = container "Another Web Application"
            webapp = container "Web Application"
            logging = container "Logging Bucket"
        }
        mobileApp -> gateway "requests"
        gateway -> webapp "passes requests"
        
        mobileApp -> logging "Writes logs" "" "Logging"
        gateway -> logging "Writes logs" "" "Logging"
        webapp -> logging "Writes logs" "" "Logging"
        
        live = deploymentEnvironment "Live" {
            deploymentNode "User's Device" {
                containerInstance mobileApp
            }
            deploymentNode "Cloud Provider" {
                deploymentNode "Gateway Node" {
                    containerInstance gateway
                }
                deploymentNode "Webapp Node" {
                    containerInstance webapp
                }
                deploymentNode "Logging Node" {
                    containerInstance logging
                }   
            }
        }
    }
    views {
        container softwareSystem "NoLoggingContainer"{
            include *
            exclude "relationship.tag==Logging"
            autolayout lr
        }
        container softwareSystem "LoggingContainer"{
            include *
            exclude "relationship.tag!=Logging"
            autolayout lr
        }
        deployment softwareSystem "Live" "NoLoggingDeployment" {
            include *
            exclude "relationship.tag==Logging"
            autolayout lr
        }
        deployment softwareSystem "Live" "LoggingDeployment" {
            include *
            exclude "relationship.tag!=Logging"
            autolayout lr
        }

        theme default
    }
}
```

Here is the output for `NoLoggingDeployment`
<img width="562" alt="Screen Shot 2022-02-17 at 5 53 42 PM" src="https://user-images.githubusercontent.com/20747904/154585012-6fcfce2c-fea8-4246-a53f-634e4124b5c5.png">

which is what I'd expect.

Here is the output for `LoggingDeployment` 
<img width="255" alt="Screen Shot 2022-02-17 at 5 53 50 PM" src="https://user-images.githubusercontent.com/20747904/154585166-1fc193ab-b8d4-4969-91ed-777ab06e5519.png">

Instead of filtering out only non-logging relationships, it appears to filter out all relationships.

Compare this though with the output of `LoggingContainer`, which works as expected
<img width="558" alt="Screen Shot 2022-02-17 at 5 56 27 PM" src="https://user-images.githubusercontent.com/20747904/154585287-39586f55-299a-4876-994a-667473d1f3c0.png">

Is there a way to achieve the filtering I'm after in the deployment view?

**Comment by simonbrowndotje** [comment]
Thanks! This should now be working as expected at https://structurizr.com/dsl and Structurizr Lite ... and it will be available in the next CLI release.

**Comment by grahamalama** [comment]
@simonbrowndotje one more question here, as I don't think this warrants a separate issue.

In the example above, after I filter out relationships, is there a way to also exclude elements that don't have a relationship?

**Comment by simonbrowndotje** [comment]
You'll need to drop out to a script to do that; for example, save the following as `myscript.groovy`:

```
import com.structurizr.model.*;
import com.structurizr.view.*;

for (View view : workspace.getViews().getViews()) {
    Set<RelationshipView> relationships = view.getRelationships();

    Set<String> elementIds = new HashSet<>();
    relationships.forEach(rv -> elementIds.add(rv.getRelationship().getSourceId()));
    relationships.forEach(rv -> elementIds.add(rv.getRelationship().getDestinationId()));

    for (ElementView elementView : view.getElements()) {
        if (elementView.getElement() instanceof DeploymentNode) {
            // do nothing ... deployment nodes are usually not connected to other elements
        } else {
            if (!elementIds.contains(elementView.getId())) {
                view.removeElement(elementView.getElement());
            }
        }
    }
}
```

(this is plain Java code, so can be better optimised for Groovy)

It can be called using this in your DSL:

```
!script myscript.groovy
```

**Comment by grahamalama** [comment]
This is great -- thanks again!
