### ISSUE TITLE
Please add Expression that allows to exclude relations that neither have element.tag==foo as source or destination

### ISSUE THREAD

**Issue by venthur** [structurizr/dsl#116]
I see that you can now with v1.18 directly in- or exclude elements including afferent and efferent couplings, which is really nice because we don't have to resort to scripts anymore. 

There's one more thing that would make this even more powerful: Since **all** possible relations will be drawn in this scenario, even the ones between the afferent and efferent elements, it would be nice to be able to exclude the ones where neither source nor destination have a specific tag. Currently I'm using something like this:

```
            !script groovy {
                view = workspace.views.getViewWithKey("my_view");
                # add external boxes that are in relation with ours
                workspace.model.softwareSystems.findAll { it.hasTag("foo") }.each{ view.addNearestNeighbours(it); };
                # but exclude the relations between the "external boxes" if
                # they're not connected to us
                workspace.model.relationships.each {
                    if (!it.destination.hasTag("foo") && !it.source.hasTag("foo")) { view.remove(it); }}
            }

```

would be nice to replace it with something like:

```
            include "element.tag==foo"
            include "-> element.tag==foo ->"
            exclude "the missing bit :)"  # i.e. the relations that don't have element.tag==foo as source or destination
```

**Comment by simonbrowndotje** [comment]
Is this the equivalent to what you're trying to do?

```
exclude "element.tag!=foo -> element.tag!=foo"
```
