### ISSUE TITLE
How can properties be shown/used within documentation and/or diagram

### ISSUE THREAD

**Issue by msche** [structurizr/dsl#12]
Within the DSL there is the option to define properties for a container/component/etc. How can these be used within the documentation and/or diagrams?

**Comment by simonbrowndotje** [comment]
The name/value properties are shown in the diagram tooltips (when enabled; screenshot attached).

<img width="687" alt="Screenshot 2020-10-19 at 14 47 27" src="https://user-images.githubusercontent.com/1009874/96459570-2ab6ba00-121a-11eb-8e36-330947198bcf.png">

**Comment by msche** [comment]
Thanks, this was exactly what I was looking for.
