### ISSUE TITLE
Reuse components across multiple containers

### ISSUE THREAD

**Issue by TheLazzziest** [structurizr/dsl#120]
Hi there! 

I find this tool very useful in order to make things right from the very beginning. 
However, I struggle to reuse a component across multiple containers. I didn't found any examples concerning this use case. According to C4Model approach, there are no restrictions in terms of component reusing. 

I am quite new in designing software, so maybe I am doing something wrong.  Here is what I want to do. 

Let say I have a set of microservices and I want to share user data across them using JWT token. The token can be decrypted by multiple microservices using something like `JWTAuthenticationMIddleware` for example. This middleware is provisioned in a separate package called `core` which is installed to every microservice which requires it. 

From C4model perspective, `core` is a component reused by several containers which can be represented in the following way:
 
`jwt.components.dsl`

```

jwtAuthMiddleware = component "JWT Authentication MIddleware" ...

```

`containers.dsl`

```

gateway = container "API Gateway"

payments = container "Microservice1" {
   !include jwt.components.dsl
   order = component "Orders"
   gateway -> jwtAuthMiddleware "Authenticate a user request"
   jwtAuthMiddleware -> order "Pass extracted user data to get order details"
}

store = container "Microservice2" {
  !include jwt.components.dsl
  bucket = component "Bucket"
  gateway -> jwtAuthMiddleware "Authenticate a user request" 
  jwtAuthMiddleware -> bucket "Pass user data to get bucket items added by the user"
}
```

`workspace.dsl`

``` 
workspace "MS" {
   ...
   store = softwareSystem "Store" {
        !include containers.dsl
   }
}
```

Thank you in advance!

**Comment by TheLazzziest** [comment]
I think the better example is to represent the connection in the following way:

```
store = softwareSystem "Store" {
        !include containers.dsl
        gateway -> payments.jwtAuthMiddleware "Extract user data from an incoming request to find user payments"
        gateway -> store.jwtAuthMiddleware "Extract user data from an incoming request to find products selected by the user" 
   }
```

**Comment by simonbrowndotje** [comment]
What you have with the `jwt.components.dsl` and `!include jwt.components.dsl` is the best approach to component reuse ... in essence, you're showing that the same component is used multiple times, in different containers.

**Comment by TheLazzziest** [comment]
Great! However, I can't do it in the way shown above because a component identifier must be **unique** across the entire **software system**. I get an error once I try to include a component in multiple containers.  
 
What I need here is to bound jwt component to a particular container. That way I could create a container namespace and attach the component to it. It helps me to keep the naming as it is and facilitate referencing to the component by other parties (containers and software systems as well). That way I could reuse the component in multiple contexts.

For the sake of clarity, let me provide another example in this case:

Suppose we have a warehouse for delivering some purchased goods. In order to send bought items to a customer it needs to get its address and a payment confirmation for example.  In order to do that the warehouse needs to use store API to get the information.
 
```
warehouse = softwareSystem "Warehouse"
store = softwareSystem "Store" {
        !include containers.dsl
        warehouse -> payments.jwtAuthMiddleware "Authenticate a request from an employee of the warehouse to get customer's payments"
        warehouse -> store.jwtAuthMiddleware "Authenticate a request from an employee of the warehouse to find purchased items" 
}
```

Right now, I can't do that because `jwtAuthMiddleware` identifier appears in multiple containers which is prohibited.

**Comment by simonbrowndotje** [comment]
You can use `!identifiers hierarchical` (see https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#identifier-scope) to better scope elements. For example:

```
workspace {

    !identifiers hierarchical

    model {
        a = softwareSystem "A" {
            service1 = container "Microservice1" {
                !include jwt.components.dsl
            }
            
            service2 = container "Microservice2" {
                !include jwt.components.dsl
            }
        }
        
        b = softwareSystem "B"
        
        b -> a.service1.jwtAuthMiddleware
        b -> a.service2.jwtAuthMiddleware
    }
    
}
```

**Comment by TheLazzziest** [comment]
Thanks, it helped!
