### ISSUE TITLE
Excluding relationships in views result in unexpected identifier "->" exception

### ISSUE THREAD

**Issue by christianlegault** [structurizr/dsl#121]
Hi, 

Using the latest "lite" version of structurizr and tryling to exclude a relationship in a view, specifying an individual relationship identifier, or use a property expression result in exception error. 

`unexpected identifier "->"`

I tried multiple combination with same results.

- * -> *:
- source -> *
- * -> destination
- source -> destination

Thank You.

**Comment by simonbrowndotje** [comment]
This was changed in the latest DSL version ([changelog](https://github.com/structurizr/dsl/blob/master/docs/changelog.md#1180-20th-february-2022)). You'll need to do this instead (notice the whole expression is quoted):

```
exclude "source -> destination"
```
