### ISSUE TITLE
[Question] - How to model relationships between deployed instances of systems?

### ISSUE THREAD

**Issue by mattkoch614** [structurizr/dsl#124]
Hi @simonbrowndotje - hopefully this is an easy answer I'm simply overlooking. What would be the recommended approach to modeling deployed instances of specific systems and code, and the interactions between them? For example, say we have an open sourced backend system with API endpoints, a database, and an admin interface. Say we also have a mobile app that communicates over REST with the aforementioned API endpoints. The backend can be deployed as a set of docker containers, or in other configurations not involving Docker should the implementer choose. The mobile app is deployed to an app store.

Is the answer for how to best model the software itself and the relationships between deployed instances to use a combination of [core C4 diagrams](https://c4model.com/#CoreDiagrams) (e.g the static structure) and then a [deployment diagram](https://c4model.com/#DeploymentDiagram) to extend that?

**Comment by simonbrowndotje** [comment]
> Is the answer for how to best model the software itself and the relationships between deployed instances to use a combination of [core C4 diagrams](https://c4model.com/#CoreDiagrams) (e.g the static structure) and then a [deployment diagram](https://c4model.com/#DeploymentDiagram) to extend that?

Yes, that should work ... the [Internet Banking System example](https://structurizr.com/dsl?example=big-bank-plc) uses this approach.
