### ISSUE TITLE
Visualize only containers that have a (tagged) relationship in a container view

### ISSUE THREAD

**Issue by bunschot** [structurizr/dsl#125]
Is it possible in a container view to display only elements that have a relationship with some give tag ("uses" in my use-case)?

So far I have managed to hide all  relationships other than those with the "uses" tag in the container view, but the view displays all containers, including those that do not have a "uses" relationship;
```
views {
   container my_container "my_container_view" "My Container View" {
      include *
      exclude "* -> *"
      include relationship.tag==uses
      autoLayout lr
  }
}
```

**Comment by simonbrowndotje** [comment]
Do you have a full workspace definition, rather than just the `views` section?

**Comment by bunschot** [comment]
Yes, here you go:
```
workspace "Example" "Example" {
    model {
        system = softwareSystem "TheSystem" {
            c1 = container "container1"
            c2 = container "container2"
            c3 = container "container3"
            
            c1 -> c2 "uses" "" "uses"
        }
        
    }

    views {
        container system "my_container_view" "My Container View" {
            include *
            exclude "* -> *"
            include relationship.tag==uses
            autoLayout lr
        }
    }
}
```

**Comment by bunschot** [comment]
To further clarify; I'd like to hide container3 from view

![image](https://user-images.githubusercontent.com/5424697/160787900-e4116122-ed05-494f-ac20-6e30439ae240.png)

**Comment by simonbrowndotje** [comment]
Thanks! In that case, no, you can't do it with the DSL. You can use a script/plugin though, and you have a couple of options, the easiest being to remove elements that have no connections:

```
workspace "Example" "Example" {
    model {
        system = softwareSystem "TheSystem" {
            c1 = container "container1"
            c2 = container "container2"
            c3 = container "container3"
            
            c1 -> c2 "uses" "" "uses"
        }
        
    }

    views {
        container system "my_container_view" "My Container View" {
            include *
            exclude "* -> *"
            include relationship.tag==uses
            autoLayout lr
        }
    }

    !script groovy {
        workspace.views.getViewWithKey("my_container_view").removeElementsWithNoRelationships()
    }
}
```

You could also write a script/plugin to find elements that have inbound/outbound relationships with a specific tag, and only add those. The above is simpler though.

**Comment by bunschot** [comment]
That did the trick! Thanks for your support.
