### ISSUE TITLE
Grammar Transforms in `nix`

### ISSUE THREAD

**Issue by blaggacao** [structurizr/dsl#127]
In order to build an organization wide component library that spans ~500 repos, I need to re-implement the GRAMMAR and it's transforms in `nix` in order to have _pinnable_ / _reproducible_ cross-repo component re-usability.

What can I do?

Where are the transforms (to JSON) happening?

Is there sort of a Backus-Naur form of the grammar?

**Comment by blaggacao** [comment]
```nix
with structurizr; {
  model.user = person "User";
  model.foo = softwareSystem "App" "Firefox, Chrome, Safari, Edge" "Browser";
  model.enterprise = enterprise "Bar" {
    /* ... */
  }; 
}
```

**Comment by simonbrowndotje** [comment]
> Where are the transforms (to JSON) happening?

It depends on what you want to do with the JSON, but most people use the [Structurizr CLI](https://github.com/structurizr/cli) or [Structurizr Lite](https://structurizr.com/help/lite). You can also build your own tooling in Java; see https://github.com/structurizr/dsl/tree/master/docs/cookbook/dsl-and-code#java for an example of what that might look like.

> Is there sort of a Backus-Naur form of the grammar?

You can find a language reference (albeit not in BNF) at https://github.com/structurizr/dsl/blob/master/docs/language-reference.md

**Comment by simonbrowndotje** [comment]
I've just done some reading about nix (it's not something that I've come across before), and if you're asking, "how do I port the DSL to nix?", the answer is that you'll need to port the following:

- [Structurizr for Java](https://github.com/structurizr/java)
- [Structurizr DSL](https://github.com/structurizr/dsl)

In essence, the DSL is a wrapper for the Structurizr for Java library, and it's this library that defines the data structures, and modelling rules.
