### ISSUE TITLE
AWS ECS Service/Clusters? 

### ISSUE THREAD

**Issue by mattkoch614** [structurizr/dsl#128]
What's the best way to represent a set of ECS clusters on AWS using the Structurizr DSL? 

https://docs.aws.amazon.com/AmazonECS/latest/userguide/clusters.html

**Comment by simonbrowndotje** [comment]
Closing this issue as it's more a question about the C4 model than the DSL - feel free to [join the Slack group](https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg) for C4 model discussion.
