### ISSUE TITLE
Multiple views for same Container

### ISSUE THREAD

**Issue by msche** [structurizr/dsl#13]
I have a container for which I want to show multiple views, One would be a view that shows the use cases that are provided by the service/container and another would be the actual components that are implemented within the container. I can create the views by having the use cases tagged and include the tag within the view and exclude it in the other view. The views are correctly created but issue is when i want to zoom in on the container view. There seems to be no way that I can enforce/select to which view I want to go. Is that assumption correct, or is there a way to somehow force/select the proper zoom view

**Comment by simonbrowndotje** [comment]
When you double-click an element to zoom-in, you'll be taken to the "first" diagram at the next level of abstraction. That ordering should be consistent with the ordering of diagrams you see in the diagram viewer/editor ... which I think can be influenced by changing the diagram key to change the ordering.

**Comment by msche** [comment]
Not exactly what I was looking for... will see whether I can find another way

**Comment by simonbrowndotje** [comment]
You can also set the `url` property for the container, for example to the URL of the diagram you want to zoom to.
