### ISSUE TITLE
Ability to implementation relationships with deployment instances

### ISSUE THREAD

**Issue by donald-richardson-dxd** [structurizr/dsl#131]
I have a message bus (RabbitMQ). Multiple instances exist on separate machines that use a "shovel" to send messages to each other. It would be useful to show the different instances able to communicate with each other. The only way I can think that would to implement this would be to implement relationships between deployment instances. Alternatively perhaps a relationship to self can be allowed, but then directionality would be an issue with deployment instances.

**Comment by simonbrowndotje** [comment]
This will work if you need a relationship between two instances...

```
workspace {

    model {
        a = softwareSystem "A"

        a -> a "Replicates data to"

        live = deploymentEnvironment "Live" {
            deploymentNode "Server" {
                a1 = softwareSystemInstance a
                a2 = softwareSystemInstance a
            }
        }
        
    }
    
    views {
        deployment * live {
            include *
            autolayout
        }
    }
    
}
```

But how are you modelling RabbitMQ?

**Comment by donald-richardson-dxd** [comment]
But what if I want a single direction? For example, a shovel sending messages from one RabbitMQ broker to another?

**Comment by simonbrowndotje** [comment]
You have a couple of options:

1. Use the view `exclude` feature to exclude one of the relationships between the instances.
2. Model the RabbitMQ brokers as deployment nodes, and the queues as C4 containers deployed inside them. This allows you to model the shovel as a relationship between deployment nodes.

I would probably lean towards option 2.

**Comment by donald-richardson-dxd** [comment]
Works for me. Can close.

From: Simon Brown ***@***.***>
Date: Monday, May 16, 2022 at 12:55 PM
To: structurizr/dsl ***@***.***>
Cc: Donald Richardson ***@***.***>, Author ***@***.***>
Subject: Re: [structurizr/dsl] Ability to implementation relationships with deployment instances (Issue #131)

You have a couple of options:

  1.  Use the view exclude feature to exclude one of the relationships between the instances.
  2.  Model the RabbitMQ brokers as deployment nodes, and the queues as C4 containers deployed inside them. This allows you to model the shovel as a relationship between deployment nodes.

I would probably lean towards option 2.
