### ISSUE TITLE
Permit "instances" as child of deploymentNode 

### ISSUE THREAD

**Issue by erwanosouf** [structurizr/dsl#133]
The dsl for deploymentNode is as follows 
```
deploymentNode <name> [description] [technology] [tags] [instances] {
    ...
}
```
With "description", "technology" and tags also permitted as children of deploymentNode element, which I personally prefer for readability.

However, the syntax forces to write all elements inline instead of as children in order to be able to specify an instance count.

What I would like to do : 
```
deploymentNode <name> {
     description ""
     technology ""
     tags ""
     instances 42
}
```
This is not valid with regards to the DSL

Or 
```
deploymentNode <name> 42 {
     description ""
     technology ""
     tags ""
}
```

This is valid with regards to the DSL but does not produces the expected output (showing the instance count on the deploymentNode).

See attached : 
- A DSL for Solution # 1 [solution1.dsl.txt](https://github.com/structurizr/dsl/files/8727608/solution1.dsl.txt)
- A DSL for Solution # 2 [solution2.dsl.txt](https://github.com/structurizr/dsl/files/8727615/solution2.dsl.txt)
- An expected output ![expected_output](https://user-images.githubusercontent.com/13438405/169256076-803859e1-6080-424d-b555-1e9690f79295.png)

**Comment by simonbrowndotje** [comment]
I've added support for the following:

```
deploymentNode <name> {
     instances 42
}
```

**Comment by erwan-osouf** [comment]
Hey @simonbrowndotje !

Do you have any idea when this will be released ?

Thanks in advance !

**Comment by simonbrowndotje** [comment]
Probably some time in July.
