### ISSUE TITLE
Title of the docs does not follow the documentation file name

### ISSUE THREAD

**Issue by williamlim16** [structurizr/dsl#143]
I just experimented with this tools and was trying to make custom docs for my company. I follow the instructions on how to make the .md file gets rendered by Structurizr [here](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#documentation). It says that Structurizr will change the name of the section from the document name and will be sorted alphabetically. But, I found that Structurizr does not do that it renders "Name" instead. Is there any updates on how the documentation works? How do I change the "Name" title?

![image](https://user-images.githubusercontent.com/48128967/178232830-22bd3df8-fe32-43d9-9d98-974f59bbba06.png)
![image](https://user-images.githubusercontent.com/48128967/178233008-21e33771-a912-4786-9542-d586d513b07c.png)

**Comment by simonbrowndotje** [comment]
“Name” is the default name of your workspace - you can override this by adding a name to your workspace definition on line 1.

**Comment by williamlim16** [comment]
Oh right, thanks for your reply.
it works!
