### ISSUE TITLE
Embed Markdown

### ISSUE THREAD

**Issue by carlosmedrano97** [structurizr/dsl#144]
Hi! Thanks for this great tool
I'm trying to document an architecture for microservices using docs and markdown
I want to document each microservice on a separate file and then add all of them into a Microservice section (different file)
Is this possible?

**Comment by simonbrowndotje** [comment]
With the default documentation importer, each file becomes a separate section. You can write your own documentation importer though, by forking/extending [DefaultDocumentationImporter](https://github.com/structurizr/documentation/blob/main/src/main/java/com/structurizr/documentation/importer/DefaultDocumentationImporter.java).

Alternatively you could pre-process all of your separate files into a single file for use with Structurizr.
