### ISSUE TITLE
Is there a way to connect perspectives between each other ?

### ISSUE THREAD

**Issue by TheLazzziest** [structurizr/dsl#146]
Hi! I wonder why the language doesn't provide any means to connect two perspectives between each other ? 

I have been using perspectives to describe processes within a system for a while. I've seen that some of them have parent-child relationships for example. Some of them shows that one process affects another one and so on. 

These connections allow to see transitions from one process to another which is quite useful. [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph) can be used to that extent in order to visualise perspectives as a bunch of interconnected processes. It will also help to mitigate logical errors in terms of an execution flow.

So I think it would be great to have such kind of functionality which can look the following way:
```dsl
...
A = component "A" {
    perspectives {
         "Parent" "Do this"
         "Parent" -> "Child" "Produce an in-process signal which is handled by another related component"
    }
}

B = component "B" {
   perspectives {
        "Child" "Do that"
   }
}
...
``` 
Let say we have CRUD process for component A. This component has a sort of broadcasting tool for propagating its changes to another components of the system. These components relate to another process which should be connected with it. Ultimately, It should increase transparency.

**Comment by simonbrowndotje** [comment]
I still don't really understand what you're trying to achieve I'm afraid, but perhaps the dynamic views are better suited to describe processes ... along with things like activity diagrams from UML. Closing this issue, as it's not something I'll likely be implementing. Sorry!
