### ISSUE TITLE
Container view for multiple containers at the same time

### ISSUE THREAD

**Issue by arieltorti** [structurizr/dsl#149]
I have a use case were we can to show to software systems in the container view like so:

I know this is not entirely aligned with the C4 model but it's a use case that I have.

When using container and system landscape views I haven't found a way to make it work, only one of the software systems is expanded, even when listing all containers instead of using `include *`.

Is there a workaround to make this work ? I was checking custom views but I haven't found much information about them.

Example DSL:

```
workspace {

    !identifiers hierarchical

    model {
        A = softwaresystem "A" {
            app = container "app"
            db = container "db"
        }
        
        B = softwaresystem "B" {
            app = container "app"
            db = container "db"
        }
        
        A.app -> B.app
    }

    views {
        container A {
            include *
            autolayout
        }

        theme default
    }
}
```

Actual result:

![image](https://user-images.githubusercontent.com/6711122/183995419-be611a87-197d-4955-8376-c0d6b6544b8a.png)

Expected result:
![image](https://user-images.githubusercontent.com/6711122/183995465-e2a53047-93cb-439b-8b64-d205321e9367.jpg)

**Comment by simonbrowndotje** [comment]
> even when listing all containers instead of using include *

That should work, for example:

```
        container A {
            include A.app A.db B.app B.db
        }
```

**Comment by arieltorti** [comment]
Ahhh I see, I was also including the software systems:
```
container A {
    include A B A.app A.db B.app B.db
}
```

Which resulted in:
![image](https://user-images.githubusercontent.com/6711122/184190006-7f14d71a-d811-4b9c-a6e5-e745a41b5262.png)

On a separate note, is there a way to show relations between software systems in container views ? Take the same example and add a new relation `A -> B`, when using the container view it's not displayed:

![image](https://user-images.githubusercontent.com/6711122/184190408-a386caa1-0524-4015-bd50-3c80e7683a64.png)

Generated from:
```
workspace {

    !identifiers hierarchical

    model {
        A = softwaresystem "A" {
            app = container "app"
            db = container "db"
        }

        B = softwaresystem "B" {
            app = container "app"
            db = container "db"
        }

        A -> B
    }

    views {
        container A {
            include A.app A.db B.app B.db
        }
    }
}
```

**Comment by simonbrowndotje** [comment]
> On a separate note, is there a way to show relations between software systems in container views

No, it's the containers that are the focus of the diagram.

**Comment by arieltorti** [comment]
Is the ordering in the `include` statement important ?

When switching the order of the elements I get different diagrams:

```
container A {
    include A.app A.db B.app B.db A B 
}
```

Renders:
![image](https://user-images.githubusercontent.com/6711122/184190806-15529d78-0706-4177-8aa3-be0b676b66d9.png)

But when the software systems are at the beginning:
```
container A {
    include A B A.app A.db B.app B.db 
}
```

It renders:
![image](https://user-images.githubusercontent.com/6711122/184191048-7f72ff75-4828-4859-a137-dc80a7a45798.png)


Is that intended ?

**Comment by simonbrowndotje** [comment]
> Is that intended ?

Yes.

**Comment by arieltorti** [comment]
Could we add that to the language reference documentation ?

Explain that ordering matters and how it impacts rendering ?
