### ISSUE TITLE
Converting a DSL into an image file

### ISSUE THREAD

**Issue by WhyNotHugo** [structurizr/dsl#15]
I can't quite figure out how to use structurizr

Using the web
------------------

- Using the cloud version, there's a [demo editor](https://structurizr.com/dsl) which I can use and render images. The weirdness about this editor is that it's not tied to my workspace, so I need copy-paste my DSL and save it into files locally. This works, but seems to be a terribly UX. It's only a matter of time before I end up losing information with poor copy-pasting.

- Via my personal workspace, there seems to be no way to _edit_ DSL. If there is, I can't figure out how to it. So it  can render, but I can't type anywhere.

Using the cli
----------------
- Using the CLI I can convert my DSL into various other formats, but not into an image file. It seems that you guys use graphviz to render the image, but the CLI cannot export to graphviz.

- I can use the CLI to upload my DSL, but that's a dead end. I then have to log into the website, and navigate my way around onto the image. For each change I make, I need to re-do the whole round trip (and this is certainly something not scriptable). Each change I make, I need to:
  - Save file.
  - Use cli to upload (this is suuuper slow!)
  - Reload the webpage

So far, it seems that just using the demo editor and copy-pasting is the best way to use structurizr (which is weird, since it makes all the paid features entirely irrelevant). Am I missing something here?

**Comment by simonbrowndotje** [comment]
To answer your questions...

### Using the web

 - The [demo editor](https://structurizr.com/dsl) is for demo purposes, and it's missing a few features (e.g. includes), but it can certainly be used if you need a quick diagram, or you want to preview changes (to answer your last question).
 - We don't provide a UI for editing the DSL. There are good text editors out there already, and somebody has written  a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ciarant.vscode-structurizr) that does some basic syntax highlighting.

### Using the CLI

 - The CLI allows you to export the DSL into a number of formats ... PlantUML, Mermaid, WebSequenceDiagrams, Ilograph, and the Structurizr web renderer. With all of these options, you'll need to use the tool's own workflow to get PNG images.
- You'll need to upload the DSL via the CLI, and then use the website (or local on-premises installation) to view the diagrams if using the Structurizr rendering option. To export the diagrams to a PNG format, you have a number of options: (1) manually by visiting the diagram viewer and clicking the export button, (2) automatically using something like Puppeteer ([example scripts](https://github.com/structurizr/puppeteer)), (3) automatically using the [image embed feature](https://structurizr.com/help/embed-image) (paid feature).

The quickest way to get some feedback is to use the demo editor, and this is particularly useful when starting a new model, or when learning about the DSL. The majority of the paid features allow teams to easily share their diagrams and documentation (e.g. role-based access, Confluence plugins, etc). If you are just looking for PNG exports, you will likely find you don't need the paid feature set.

**Comment by WhyNotHugo** [comment]
Thanks for all the clarifications!

It looks like puppeteer might do what I need. However, there seems to be an incredibly high level of complexity. To convert a DSL into a PNG I need to:

- I can use any local editor to edit the file.
- I then need to the pretty heavy java CLI to push to the hosted version.
- Run puppeteer and a lot of extra scaffold to go through the process of fetching the image.
- Download the image.

I wonder if it might be possible to just add an option to export a PNG via the cli? What's the point of requiring a webserver, a browser, and complex automation in the middle?

**Comment by simonbrowndotje** [comment]
Thanks, you're welcome. With the Structurizr cloud/on-premises installation, the diagrams are actually rendered in a web browser (i.e. client-side), using a JavaScript framework, which ultimately creates SVG. Without a web browser, there are no diagrams, so it's not really viable to add PNG export to the Structurizr CLI. (this is why we provide the automatic PNG export/embed as a paid feature)

I believe that PlantUML and Mermaid allow you to export PNG files via the command line, so perhaps take a look at those as your diagram renderer tooling instead.

**Comment by simonbrowndotje** [comment]
I forgot to ask ... why are you looking to create PNG versions of the diagrams?

**Comment by WhyNotHugo** [comment]
> I forgot to ask ... why are you looking to create PNG versions of the diagrams?

So as to share them with the rest of my team. The DSL is good for expressing but not for sharing/presenting.

**Comment by WhyNotHugo** [comment]
I think all my doubts have been covered. Thanks for your time!

**Comment by simonbrowndotje** [comment]
> So as to share them with the rest of my team. The DSL is good for expressing but not for sharing/presenting.

Sharing/presenting is exactly what the paid feature set is designed to help with: role-based access/sharing link to view the diagrams, double-click to zoom functionality built in, tooltips for more information, step-by-step animations, etc.

**Comment by WhyNotHugo** [comment]
Yeah, that doesn't work for us, again, too much overhead, too much complexity.
We can't have our diagramming processes be as complex as our actual business processes. :disappointed:

**Comment by simonbrowndotje** [comment]
It's all trade-offs ... the simplest approaches (e.g. a whiteboard or Visio, etc) have a low barrier to entry, but they don't provide any guidance, and you have to manually keep multiple diagrams in sync with each other. All of the text-based approaches (PlantUML, Mermaid, WebSequenceDiagrams, etc) require a toolchain to be built in order to export/share diagrams, with only the Structurizr DSL being model-based so that you can create multiple diagrams from a single model. The way I use the DSL myself is:

- edit DSL in a text editor
- commit changes to my repo
- push to my cloud workspace using the CLI

I have the sharing link enabled for my workspace (which saves me signing in), and the diagrams are embedded via Structurizr's Markdown/AsciiDoc documentation feature ([example](https://structurizr.com/share/36141/documentation#%2FInternet%20Banking%20System:All)), so everything is located in a single place. Many teams embed diagrams directly from the Structurizr cloud/on-premises installation via the Confluence macros too, and never use the Structurizr service directly themselves. Both approaches are pretty optimised.

As I said, any text-based approach you choose will require a toolchain. If you just need PNGs, the Structurizr DSL with PlantUML or Mermaid output (via the CLI `export` command -> https://github.com/structurizr/cli/blob/master/docs/export.md) might provide a shorter workflow.

**Comment by simonbrowndotje** [comment]
With your Python background, you might want to try this -> https://diagrams.mingrammer.com (although you'll need graphviz too).
