### ISSUE TITLE
Filter by Tags and Relationships not working like expected in System Landscape

### ISSUE THREAD

**Issue by goggi** [structurizr/dsl#152]
Imagine this scenario:

workspace {
  model {
    service2 = softwareSystem "Service 2" {
      tags = "Event 1, Event 2"
      event2Process = container "Event 2 Process" "" "" {
        tags "Event 2"
      }
      event1Process = container "Event 1 Process" "" "" {
        tags "Event 1"
      }
    }
    service1 = softwareSystem "Service 1" "" "" {
      tags "Event 1, Event 2"
      event2Create = container "Create Event 2" "" "" {
        tags "Event 2"
        -> event2Process "" "" " Event 2"
      }
      evemnt1Create = container "Create Event 1" "" "" {
        tags "Event 1"
        -> event1Process "" "" "Event 1"
      }             
    }
  }
}

If I filter on tag Event 1, then the relationship between Service 1 and Service 2 wont be included, as that relationship inherits the relationship specified in ecent2Create (-> event2Process "" "" " Event 2"). This makes it so that the Event 1 tag is not specified in the relationship between Service 1 and Service 2. 

![image](https://user-images.githubusercontent.com/1946339/185152909-8b138315-2f50-4aa9-b71d-cf01adb92dc4.png)

Ideally all tags from event2Create and evemnt1Create should be available in the relationship between Service 1 and Service 2, or am I thinking wrong here?
[recording_20220817-155334.webm](https://user-images.githubusercontent.com/1946339/185152029-c809ae5d-1478-4e1d-8e5b-680c58683b8c.webm)

**Comment by simonbrowndotje** [comment]
Feel free to include a full DSL example that I can paste into https://structurizr.com/dsl and I'll take a look.

**Comment by goggi** [comment]
Sorry, having some issues with the add code tag, but the code I pasted should work now

**Comment by simonbrowndotje** [comment]
Thanks, but there doesn't seem to be a system landscape view definition, so I'm unsure what you're seeing vs what you're expecting to see.

**Comment by goggi** [comment]
Go to DSL and render the code 

workspace {
model {
service2 = softwareSystem "Service 2" {
tags = "Event 1, Event 2"
event2Process = container "Event 2 Process" "" "" {
tags "Event 2"
}
event1Process = container "Event 1 Process" "" "" {
tags "Event 1"
}
}
service1 = softwareSystem "Service 1" "" "" {
tags "Event 1, Event 2"
event2Create = container "Create Event 2" "" "" {
tags "Event 2"
-> event2Process "" "" " Event 2"
}
evemnt1Create = container "Create Event 1" "" "" {
tags "Event 1"
-> event1Process "" "" "Event 1"
}
}
}
}

You will see this:
![image](https://user-images.githubusercontent.com/1946339/185158641-f747ff27-99d8-4a82-aac7-0a443b8fffff.png)

Now filter on tag Event 1 from the bottom list and you will see this.
![image](https://user-images.githubusercontent.com/1946339/185159073-9a017bbc-2fdb-42bb-bb06-6e8206b9e2a4.png)
The relationship between Service 1 and Service 2 is not highlighted. 

I am expecting it to be highlighted as both tag Event 1 and Event 2 are available in the relationships defined to containers within Service 2. Now there is a workaround by adding a relationship directly on Service 1 to Service 2. But it would be good if the relationship that is automatically generated between Service 1 and Service 2 it inherits all the tags:
-> event2Process "" "" " Event 2"
-> event1Process "" "" "Event 1"

**Comment by goggi** [comment]
I understand, was hoping that the implied relationship would be a combination of all the container2container relationships, not only the first defined one. But I understand if that makes it complicated.

**Comment by goggi** [comment]
Thanks for the clarification!!! I'm really enjoying working with structurizr!! Thanks for a great tool

**Comment by simonbrowndotje** [comment]
> I understand, was hoping that the implied relationship would be a combination of all the container2container relationships, not only the first defined one. But I understand if that makes it complicated.

The implied relationships strategy is pluggable, and you can create your own version if desired by implementing this interface -> 
https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/ImpliedRelationshipsStrategy.java
