### ISSUE TITLE
Default Views + Dynamic View

### ISSUE THREAD

**Issue by jaimegarcia** [structurizr/dsl#154]
Hi, great product, wondering if there is a way to use the default views plus some or all Dynamic Views

As soon I add a dynamic view I loose the default ones.

According to docs Default don't include those
https://github.com/structurizr/cli/blob/master/docs/defaults.md

**Comment by simonbrowndotje** [comment]
Thanks! Yes, you can use a script to create the default set of views, then add more. For example:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        !script groovy {
            workspace.views.createDefaultViews()
        }

        dynamic * "key" {
            user -> softwareSystem
            autoLayout
        }
    }

}
```

(note that scripting is only enabled when using the CLI or Lite)

**Comment by jaimegarcia** [comment]
Amazing! Thank you
