### ISSUE TITLE
Urls do not work when clicking into lower levels

### ISSUE THREAD

**Issue by kawigreen14r** [structurizr/dsl#155]
Hi,  Not sure if it's just me, but when using urls with lower level elements, they show up in the DSL view with the "**+#**", but you can only click into the lower level.  Is this a bug that a described url cannot be invoked, or is there some hidden way to click the prescribed url?  And if its a bug, is this something that can be remedied anytime soon?

Consider the following code:

workspace {

    model {
        u = person "User"
        s = softwareSystem "Software System" {
            webapp = container "Web Application" {
            url https://www.google.com/
                c1 = component "Component 1"    
                c2 = component "Component 2"    
            }
            database = container "Database"
        }

        u -> c1 "Uses"
        c1 -> c2 "Uses"
        c2 -> database "Reads from and writes to"
    }

    views {
        container s {
            include *
            autolayout lr
        }
        component webapp {
            include *
            autoLayout lr
        }
    }
    
}

It produces this using the online DSL, which behaves the same in the Lite version, where it knows there is a link AND a lower level:

![image](https://user-images.githubusercontent.com/38863224/186230356-380f6fd3-26ba-4f7e-b5ff-0ed59003a0f5.png)

Notice the **+#** symbol that says it recognizes there is an url, but I can't get it to produce the hand icon anywhere to open the link, it can only drill down to the next level view:

![image](https://user-images.githubusercontent.com/38863224/186231041-3f511fe1-e4dd-4511-9024-539869d2b18e.png)

Hoping someone can help.......

**Comment by simonbrowndotje** [comment]
If an element has both a "zoom-in" and a hyperlink set (`+#`), double-clicking the element will zoom-in, and double-clicking with the `Alt` key pressed will open the hyperlink.

**Comment by kawigreen14r** [comment]
Hallelujah, that worked, thanks for the response, I tried shift, ctrl, ctrl-shift, alt-ctrl, but not just alt!  Thanks
