### ISSUE TITLE
Bug rendering enterprises in systemLandscape & systemContext views

### ISSUE THREAD

**Issue by qequ** [structurizr/dsl#159]
Having a dsl like this
```
workspace {

    !identifiers hierarchical

    model {

        enterprise "enterprise1" {
            A = softwaresystem "A" {
                app = container "app"
                db = container "db"
            }

        }

        enterprise "enterprise2" {
            B = softwaresystem "B" {
                app = container "app"
                db = container "db"
            }

        }

        A -> B
    }

}

```

when running structurizr cli with plantuml as output `enterprise1` is lost and both software systems are put inside `enterprise2`. It seems like cli grabs the last enterprise and puts every software system inside of it.

![structurizr-SystemLandscape](https://user-images.githubusercontent.com/19431622/190714333-88cf7eca-79b8-4dc8-b674-055a932393d0.png)
![structurizr-A-SystemContext](https://user-images.githubusercontent.com/19431622/190714823-b9a33212-e308-454e-b01b-e0fe4a952f91.png)
![structurizr-B-SystemContext](https://user-images.githubusercontent.com/19431622/190714832-6905bea5-0e7b-46cb-9dac-de3ddb1fb4d7.png)

 
CC: @dgutson

**Comment by simonbrowndotje** [comment]
A model only has a single enterprise (see https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#enterprise for more), so what you're seeing is the correct behaviour. I'll add some code to throw an error if a DSL definition tries to set the enterprise more than once.

The group feature (https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#group) may provide what you're looking for.

**Comment by dgutson** [comment]
If a model has a single enterprise, why it isn't just another attribute, rather than being a language construct by itself which can have nested content? I think the grammar is misleading by allowing ```enterprise <name> { ... ```

**Comment by simonbrowndotje** [comment]
It essentially is a single attribute, but the `enterprise <name> { ...` syntax was chosen to support some backwards compatibility with the original Java library, which I started building in 2014, particularly with regards to people/software systems being marked as "internal" (inside the `enterprise` block) vs "external" (outside) to the enterprise. From the docs:

> Any people or software systems defined inside this block will be deemed to be "internal", while all others will be deemed to be "external".

**Comment by dgutson** [comment]
I think that, at least, there should be an error message when more than one enterprise is specified. The group alternative was the solution, thanks.

**Comment by simonbrowndotje** [comment]
> I think that, at least, there should be an error message when more than one enterprise is specified.

I agree, and I said the same in response to @qequ ...

> I'll add some code to throw an error if a DSL definition tries to set the enterprise more than once.

The commit referenced above your comments added this behaviour -> https://github.com/structurizr/dsl/commit/6cd4240253b34d6653e3a314617dc0a7ce3b61c0

**Comment by dgutson** [comment]
Great work, sorry about reading too fast.
Looking forward to use the latest version!
