### ISSUE TITLE
Add a passthrough relationship

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#160]
Let's assume there's an ingress.
Let's assume X talks to Y through the ingress.
If I put all the relationships through the ingress, the peer-to-peer information (from/to) is lost:
```
X1 -> ingress
X2 -> ingress
ingress -> Y1
ingress -> Y2
```

I propose to be able to specify a "pass through" relatinship this way:

```
X1 -> ingress -> Y1
X2 -> ingress -> Y2
```

**Comment by simonbrowndotje** [comment]
I took a look at doing this, and it's not particularly straightforward given how the DSL currently works. I'll keep this in the back of my mind, but closing the issue for now.
