### ISSUE TITLE
Possible to define a one-off relationship for a non-dynamic view?

### ISSUE THREAD

**Issue by bensmithett** [structurizr/dsl#161]
Thanks for the very useful tool! I've read [modelling multiple relationships](https://dev.to/simonbrown/modelling-multiple-relationships-51bf) and wanted to confirm whether something like this is possible?

Here's a contrived example:

```
workspace {
  model {
    customer = person "Customer"
    onlineBookStore = softwareSystem "Online book store"
    warehouse = softwareSystem "Warehouse fulfillment system"
    emailSystem = softwareSystem "Platform for sending emails"

    customer -> onlineBookStore "Browses and makes purchases using"
    onlineBookStore -> warehouse "Sends customer orders to"
    onlineBookStore -> emailSystem "Sends email receipts using"
    emailSystem -> customer "Sends emails to"
  }

  views {
    systemContext onlineBookStore "Overview" {
      include *
      autoLayout
    }

    systemContext onlineBookStore "Fulfillment" {
      include *
      exclude emailSystem
      autoLayout
    }
  }
}
```

As per that book store example, I've defined a fairly general relationship between my customer and the software system.

Now I want to define a view around a focused "Fulfillment" use case. 

A standard `systemContext` view with some `include` and `exclude` gets me 99% of the way there. But I really want to define a more specific relationship for this view. I know I can achieve this with a dynamic view...

```
dynamic * {
  customer -> onlineBookStore "Places order using"
  onlineBookStore -> warehouse
  autoLayout
}
```

... but that means...

- Relationships are numbered, when I'm not really trying to show an ordered process (I just want to define a more specific relationship)
- I need to re-specify all of `onlineBookStore`'s relationships just to get them to appear

I could also just define that really specific relationship and give it an identifier...

```
# model
customer -> onlineBookStore "Browses and makes purchases using"
specificRel = customer -> onlineBookStore "Places order using"
```

```
# views
systemContext onlineBookStore "Fulfillment2" {
  include *
  exclude emailSystem
  exclude "customer -> onlineBookStore"
  include specificRel
  autoLayout
}
```

...but then that relationship exists in all my other views unless I explicitly exclude it. (Is there a way to globally exclude a specific element/relationship/tag from _all_ views unless explicitly included?)

---

Am I missing an easier way to achieve this? Something like (here comes the pseudocode) 

```
systemContext onlineBookStore "Fulfillment2" {
  include *
  exclude emailSystem
  exclude "customer -> onlineBookStore"
  
  # Define a relationship scoped to this view, like I can with dynamic
  customer -> onlineBookStore "Places order using"

  autoLayout
}
```

Thanks again!

**Comment by simonbrowndotje** [comment]
> But I really want to define a more specific relationship for this view.

Structurizr is model-based, so there's no way to define view-specific elements/relationships I'm afraid.

**Comment by bensmithett** [comment]
👍 thanks!
