### ISSUE TITLE
Disable implicit relations in dynamic views

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#166]
According to the documentation:
> if a relationship between the two elements does not exist in the static model, the DSL parser will automatically create it for you.

I personally would consider this an error: a view is a view, and should not change the topology of the entities.
This being said, I propose some directive to turn off the automatic creation of relationships in the dynamic views, for example, `!disableAutoRelCreation` or alike.

**Comment by dgutson** [comment]
@simonbrowndotje what do you think about this?

**Comment by dgutson** [comment]
"response" messages should still be allowed (that is, when there exists an `a->b` relationship, then `b->a` should be accepted).

**Comment by simonbrowndotje** [comment]
It was a convenience feature, but I can see how it might be confusing, so I've removed it.
