### ISSUE TITLE
!include is ignored within properties block

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#167]
When having
```
    views {
        properties {
            "plantuml.includes" "extra_styles.puml"
            "c4plantuml.tags" "true"
            "plantuml.legend" "false"
            !include sequenceDiagrams.dsl
        }
```
the `!include` directive is ignored. Moreover, the file may not exist and nothing happens.

**Comment by dgutson** [comment]
could you please generate the docker image?

**Comment by simonbrowndotje** [comment]
I'm travelling for the next few days, and don't have a fast/good enough Internet connection to upload a new Docker image, but it's on my todo list when I return home. If you're in a rush, you can build the DSL parser from the source, and replace the `structurizr-dsl-*.jar` file in the CLI.

**Comment by dgutson** [comment]
ok thanks, did that as a temporal solution.

**Comment by dgutson** [comment]
@simonbrowndotje just in case something went wrong> there is a new docker image to pull, but it still lacks many of the changes you did on Friday.

**Comment by dgutson** [comment]
Friendly reminder to update the docker image :)

**Comment by simonbrowndotje** [comment]
The Docker image has been updated a number of times over the past week; see https://hub.docker.com/r/structurizr/cli/tags for more details.

Aside from some very recent changes, everything listed on the [changelog](https://github.com/structurizr/export/blob/main/docs/changelog.md) (even the "unreleased to Maven Central" changes) and [PlantUML exporter documentation](https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml) should be available via the CLI. If this is not the case, please open a new issue with a specific example that fails.

**Comment by dgutson** [comment]
Ok, just FYI, this very fix is not in there.

**Comment by simonbrowndotje** [comment]
It seems to work for me. Can you provide a specific example that doesn't work?

**Comment by dgutson** [comment]
I found the problem by looking at the changelog:
> Renamed `plantuml.sequenceDiagrams` to `plantuml.sequenceDiagram`

I think that unrecognized properties should throw an error. I'll open an issue for that.
