### ISSUE TITLE
Only first relation is displayed only in container view

### ISSUE THREAD

**Issue by arthis** [structurizr/dsl#169]
Hi all,

I am pretty new to C4 modelling, and maybe I am doing something wrong or not possible yet.

I am using the latest version of  structurizr on premises from docker  :

`docker run -d -p 8080:8080 -v /mnt/c/ISAGRI/Archi:/usr/local/structurizr structurizr/onpremises`

I am running the following workspace :

```
!constant DOCUMENTATION_BASE_URL "locahost:8080"


workspace GestionInterne "Gestion Interne - Agenda" {

    

    model {
        userCabinetComptable = person "SomeUser" "Utilisateur lambda"
        
        
        clientSide = softwareSystem "SomeClient" "local" {


            messageApp = container "Message Sending  Application" "fetch/push Nack messages" ".net core app" {
            }
            

            spaMyApp = container "My application" "spa" "Angular" {
            }
        }
        

        cloud = softwareSystem "azure cloud"  "internet" {
            
            apim = container "APIM" "Api management" "Azure" {
                url "http://${DOCUMENTATION_BASE_URL}/docs/general/apim.md"
            }

        }
        

        clientSide -> cloud "Uses synhronization flows" "Https" 
        clientSide -> cloud "Uses" "Https"


        messageApp -> apim "Uses Synchronization flows" "Https"
        spaMyApp -> apim "Uses" "Https"

    }

    views {
        

        systemLandscape  overview "overview landscape" {
            include *
        }


        container clientSide containerViewClientSide "Containers Client Side" {
            include *
        }

        container cloud containerViewCloud "Containers Cloud" {
            include *
        }

        theme default
    }

}
```

I was expecting the containerViewCloud to display both relationships :
 - "Uses Synchronization flows" "Https"
 - "Uses" "Https"
 
Whereas, it is only the first link that is taken is always displayed. Is there something missing in my understanding?

![image](https://user-images.githubusercontent.com/1129668/198222540-3c466c23-5855-4105-a13a-cc76b199c274.png)

for the record here are the other views perfectly well displayed  : 

system Landscape :

![image](https://user-images.githubusercontent.com/1129668/198223270-75f6164c-9bcc-4b04-9557-ed36b5bcdd02.png)

container client side : 

![image](https://user-images.githubusercontent.com/1129668/198223377-2139a6f6-2ace-4b3a-8df2-39c8ce61d1f9.png)

**Comment by arthis** [comment]
I have found a solution so I will close the issue. You can reopen it if you feel like it is something to address to.

I have added the following to express those relations :

```
clientSide -> apim "Uses Synchronization flows" "Https"
clientSide -> apim "Uses" "Https"
```

These will display nicely.

**Comment by simonbrowndotje** [comment]
I suspect you're seeing this behaviour -> https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships
