### ISSUE TITLE
Is there a reason for not having component instance in deployment environment

### ISSUE THREAD

**Issue by codersparks** [structurizr/dsl#17]
I'm trying to model a system at work that is effectively a system of services built on AWS components. Trying to apply the c4 model to this situations I have:

Context: The system with it's external services (for example email provider) and users
Container: Each of the containers are the individual services that consist within the system (e.g. user management, sign in, asset)
Component: Each container is then broken down into it's components, for example asset management consists of (user gateway (AWS API Gateway), user api Controller (AWS Lambda), service gateway (AWS API Gateway), service api controller (AWS Lambda).

I'd like to be able to create deployment views for each of those components (similar to the AWS example on the website), however, from the documentation it appears that there is only the option for creating an instance for softwaresystem and container.

Am I missing something? or am I completely using the model wrong? or would it be possible to add the ability to create a component instance  within the DSL?

Thanks

**Comment by simonbrowndotje** [comment]
In the C4 model, it's containers that are the deployable things, not components. There are some [FAQs on the C4 model website](https://c4model.com/#FAQ) that discuss modelling serverless/microservices architectures that might help ... but it sounds like you're using the model in a way it wasn't designed.

**Comment by codersparks** [comment]
Thanks for the clarification Simon, I'll have a read and revisit how we're using the model.

I'll close for now
