### ISSUE TITLE
Show all relationships instead of the first one

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#170]
Consider this DSL:
```
workspace "Test Product Architecture" "Model of the Test Platform." {

    !identifiers hierarchical

    model {
        ss = softwaresystem "SS" "Software System" {
            cont1 = container "Container1" {
                comp11 = component "Component11"
                comp12 = component "Component12"
            }

            cont2 = container "Container2" {
                comp21 = component "Component21"
            }

            cont1.comp11 -> cont2.comp21 "Relation1"
            cont1.comp12 -> cont2.comp21 "Relation2"
        }
    }

    views {
        container ss {
            include *
            autoLayout
        }

        theme default

    }
}
```

The generated output is:
![image](https://user-images.githubusercontent.com/9671770/198712928-48d24d4f-a652-4888-b6ee-605d8b352de6.png)

This is, only the description of the first relationship is shown (both PlantUML exporters).

I propose to have a property in the view, to enable the concatenation of all the descriptions of the relationships that are "merged". In this case, I propose that the description of the merged relation would be `Relation1\nRelation 2`. I didn't research how to show this properly in PlantUML.
I changed the relationship line in the resulting C4-Plantuml file as this:
```
Rel_D(SS.Container1, SS.Container2, "Relation1\nRelation2", $tags="")
```
but the resulting drawing is exported as
![image](https://user-images.githubusercontent.com/9671770/198713758-c1321e6f-8c61-40ff-ab25-1b86b4b8db85.png)

I just expect the relation texts one below the other.

Note: relationship texts should be unique, that is, if there are more than one relationship with the same text, the merged (concatenated) text should not contain duplicates.

CC @qequ

**Comment by simonbrowndotje** [comment]
I’ve transferred this issue to the DSL repo, because it’s not related to exporting views. What you’re seeing is the [implied relationships feature](https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships). You can disable this behaviour, or create your own implied relationships strategy to aggregate relationships at higher levels of abstraction. Let me know if you want to do this, and I’ll provide you some more information.

**Comment by dgutson** [comment]
@simonbrowndotje the implied relationships feature is just great. I just need to specify this "merging" (or concatenating) behavior because otherwise the feature is lossy, and I need it to be lossless. So yes, please do provide me some more information, greatly appreciated.

**Comment by dgutson** [comment]
> A better approach is to collapse multiple relationships into a single description
That, but automatically by concatenation rather than me summarizing it.

**Comment by simonbrowndotje** [comment]
Thinking about this some more, implementing your own implied relationships strategy will not work, because relationship descriptions are immutable.

Therefore, I think you’re going to have to: 1. disable the implied relationships feature in your workspace and 2. write yourself a plugin that you run in your DSL before views are created, the function of which will be to create the missing relationships at the higher levels of abstraction, with the concatenated descriptions. Somebody may have done something similar on the Slack group, so perhaps it’s worth asking there before spending too much time on this.

**Comment by dgutson** [comment]
Maybe adding a "callbacks" or "hooks" feature would be great. For example, a callback for the implied relationships, so my callback gets called either for each participating relationship (like a lambda), and/or once for all the relationships (a callback receiving all the relationships in a container, and whose responsibility is to generate a new resulting relationship).
That would allow me to add the "concatenation" behavior as a particular case, being able to apply truncation, size limit, etc.
This way the script would be minimalistic to the "policy" about what to do with many relationships, and the same mechanism could be applied for other similar situations.
The main difference with the `script` idiom is that there would be a specific event, with a specific signature.
It would be something like
```
callback <hook name> <language> {
    body
}
```

in this case, it could look like
```
callback impliedRelationships java {
    Relationship impliedRelationships(Relationships [] array) {
    }
}
```
(sorry I don't know Java :) )

**Comment by dgutson** [comment]
Or, it could also be the same callbacks/events/hooks idea but with a plugin in order to not mess the DSL. People would just register them.

**Comment by dgutson** [comment]
Or.. there could be just a predefined collection of implied-relationship-strategies to pick from, being "pick the first name" the default (current one), "concatenate-all", etc. I'm also good with this approach.

**Comment by simonbrowndotje** [comment]
The existing implied relationships functionality is essentially done via a callback each time a relationship is added to the model -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/ImpliedRelationshipsStrategy.java#L15

As I said though, this approach won't work given what you're trying to do. You'll need to wait until the end of model creation in order to aggregate all of the relationships at the higher levels of abstraction and concatenate the relationship descriptions. In short, you're going to need to write some Java code, I'd suggest as a plugin, I'm afraid.

**Comment by qequ** [comment]
@simonbrowndotje do you have a link to structurizr's slack to join?

**Comment by qequ** [comment]
@simonbrowndotje you suggested using plugins to create the missing relationships with the full descriptions, but with plugins it's not possible to access the `addRelationship` method of the `Model` class; that method is set as private. What do we do now?

**Comment by simonbrowndotje** [comment]
You will need to do something like this:

```
Component component1 = ...
Component component2 = ...
Container container1 = component1.getContainer();
Container container2 = component2.getContainer();

container1.uses(container2, component1.getDescription() + "\n" + component2.getDescription());
```

**Comment by qequ** [comment]
@simonbrowndotje  the `uses` method works fine creating relations, but the solution you gave was too specific for the case you know it's components and you know you have to get the container using  the `getContainer` method. 
I tried using the more general `getSource` / `getDestination` methods for each relation and then getting the parents of each relation element with `getParent`. The issue with this is that these methods return `Element` objects, and when I want to use the `uses` method it requires a `CustomElement` object, when both objects are `Element`s. Why the uses method for `Element` requires a `CustomElement` ? is there a workaround for this, like setting an `Element` as a `CustomElement`?

**Comment by simonbrowndotje** [comment]
It's Java, so you can use an instance check and cast:

```
if (source instanceof Component && destination instanceof Component) {
  Component component1 = (Component)source;
  Component component2 = (Component)destination;
  ... more code
}
```

All of the `uses(...)` methods are defined on [StaticStructureElement](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/StaticStructureElement.java), which `Component`, `Container`, and `SoftwareSystem` all extend. `CustomElement` is something different.

**Comment by qequ** [comment]
@simonbrowndotje what implied relationships generation strategy is used by default?

**Comment by qequ** [comment]
@simonbrowndotje the `uses` method only accepts Component, Container, SoftwareSystem or CustomElement, but I have a relation from an Element to a Person that is being lost because I can't add it with the uses method. Is there a workaround for this?

**Comment by simonbrowndotje** [comment]
You can use the [delivers(...)](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/StaticStructureElement.java#L185) methods that are defined on `StaticStructureElement`. Closing this issue now as it's now longer related to the DSL.

**Comment by dgutson** [comment]
Thanks! Super useful.
