### ISSUE TITLE
Trigger an error on unrecognized properties

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#173]
I spent a long time trying to find the reason why sequence diagrams were not shown.
It turned out that there was this line in the changelog that I missed:
> Renamed `plantuml.sequenceDiagrams` to `plantuml.sequenceDiagram`

I propose to throw an error on unrecognized properties. This would had help me to avoid wasting so much time. Likewise for typos.

**Comment by simonbrowndotje** [comment]
Unfortunately this isn't really viable, given that people might be using their own properties ([example](https://github.com/Riduidel/aadarchi/issues/274#issuecomment-1301747404)).

**Comment by dgutson** [comment]
In that case, what about "declaring" non-standard properties?
```
declare {
    property name "description"
}
```
This would also help documentation for users and prevent typos, help to detect breaking changes such as `sequenceDiagram/s`.

**Comment by dgutson** [comment]
Moreover, there could be a property `force.declare.properties` to control this behavior.

**Comment by simonbrowndotje** [comment]
If you'd like to perform further validation on your workspace, I'd recommend writing a DSL plugin to do this.
