### ISSUE TITLE
APIs as first class citizens 

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#176]
Maybe this is more C4 than structurizr.
I wanted to propose the ability to specify the case when a component has more than one API (it may have different _types_ like REST, GraphQL, CLI, and many of the same type). This way these interfaces could show up as a special border in notational terms, and relationships destination could be set to which interface.
Maybe something like
```
    component client = "client"
    component server = "Server" {
        api a1 = "Orders"  "" "REST"
        api a2 = "CLI" "CLI Used by deamon" "CLI"
         }
         # option 1
        client -> server "orders" "" "" a1

         #option 2
         a1 {
               client ->
          }
```

Not fun of any syntax options though.

**Comment by dgutson** [comment]
As you know, PlantUML already supports interfaces as a keyword as part of the UML components diagram.
I could workaround this "graphically" by (ab)using components representing interfaces, use an "interface" tag and setting the shape as a circle to match the component diagram notation. But I think that having native support enhances the semantic.
I do want to stay in C4, and I am not interested in classic UML: is this request aligned with the design principles and philosophy of C4?

**Comment by simonbrowndotje** [comment]
> is this request aligned with the design principles and philosophy of C4?

It's not I'm afraid. As I said before, I'd probably recommend using the C4 model in conjunction with UML given its richer semantics.
