### ISSUE TITLE
Document what is a 'relationship identifier'

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#177]
The DSL documentation mentions many times the term "relationship identifier" but I don't what it is, since it is never defined.

**Comment by dgutson** [comment]
Examples:
```
<element identifier> -> <element identifier> [description] [technology]
<relationship identifier> [description]
```

or

>The `!identifiers` keyword allows you to specify that element identifiers should be treated as `hierarchical` (relationship identifiers are unaffected by this setting).

**Comment by dgutson** [comment]
@simonbrowndotje I'll go and visit the penguins with my family. If you fix this documentation issue, I'll take a picture of a penguin for you and will attach it here.

**Comment by dgutson** [comment]
@simonbrowndotje as a proof of good will, I'm sending the first part. If you document what a relationship identifier is, I will post the complete penguin I took for you :)
![20221121_213834](https://user-images.githubusercontent.com/9671770/203186461-4b523010-569b-409e-aae8-7942c0a12a98.jpg)

**Comment by dgutson** [comment]
That is a very useful feature, and a very clear example. I suggest you add it to the documentation.
Nobody here thought about `id = a->b` by reading the documentation as is now.

**Comment by simonbrowndotje** [comment]
Done.

**Comment by dgutson** [comment]
`oath = daniel -> simon "send penguin"`
![20221117_153056](https://user-images.githubusercontent.com/9671770/203297420-90cb92d9-db22-4348-b46e-5a1e55568dc5.jpg)
