### ISSUE TITLE
Allow tags in  dynamic view relationships

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#178]
Relationships in dynamic views don't allow to specify a tag, which would make sense when only "instantiating" previously defined relationships. However, dynamic views do accept new relationships that it will define. In this case, it does make sense to be able to add a tag.
This is specially useful if I don't want the relationship to show up in other diagrams, so I can use `exclude` .

**Comment by simonbrowndotje** [comment]
The recommended approach here is to define relationships first if you need to add tags, properties, etc.
