### ISSUE TITLE
Support for multiple `enterprise` blocks

### ISSUE THREAD

**Issue by JadedEvan** [structurizr/dsl#179]
As a newcomer to the C4 model I find myself a bit confused about the limitation of having a single `enterprise` in my model. Let's take a primitive example - I build a mobile app (a Software System)(my Enterprise) that depends on AWS (a Software System)(a different Enterprise).

Would it not be appropriate to represent both my enterprise (my mobile app and whatever other systems) as well as the _external_ enterprise of AWS? I think it becomes easy to imagine the value in representing multiple enterprises within a system.

Thanks for reading!

**Comment by simonbrowndotje** [comment]
The underlying data model only supports single a enterprise, so you may want to look at the `group` feature instead -> https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#group

**Comment by dgutson** [comment]
Check #159
