### ISSUE TITLE
Add support for optionally including all "external" relationships on views

### ISSUE THREAD

**Issue by cohen990** [structurizr/dsl#182]
Hi

I find myself trying to draw up system landscapes but I want to show the system and the connections that that system has with other systems.

I've found the only way to do that is to manually include every system that you know needs to be included. This is not sustainable as a DSL grows since you'll need to remember to add new systems to the landscape whenever you need to.

Below I've provided a DSL to demonstrate my intentions along with proposed syntax

```
workspace "Example" "Example Workspace" {

    model {
        enterprise "Enterprise" {
            system = softwaresystem "Target System" "The target system" 
            
            otherSystem = softwaresystem "Other System" "Some Other System" 
            
            distantSystem = softwareSystem "Distant System" "Some distant system" 

            disconnectedSystem = softwaresystem "Disconnected System" "Some Disconnected System" 
        }
        
        system -> otherSystem "says hi"
        otherSystem -> distantSystem "says hi"
    }

    views {
        systemlandscape "FullSystemLandscape" "Full Landscape"{
            include *
            autoLayout
        }

        systemlandscape "SystemLandscape" "Actual Landscape"{
            include system
            autoLayout
        }

        systemlandscape "ProposedSystemLandscape" "Proposed Landscape""{
            include system otherSystem
            autoLayout
        }
        # This is the syntax I'm proposing to achieve the proposed landscape
        # systemlandscape "ProposedSystemLandscape" {
        #    include system
        #    renderedRelationshipDistance 1
        #    autoLayout
        #}

        systemlandscape "ProposedSystemLandscape2" "Proposed Landscape with Distance 2""{
            include system otherSystem distantSystem
            autoLayout
        }
        # This is the syntax I'm proposing to achieve the proposed landscape
        # systemlandscape "ProposedSystemLandscape" {
        #    include system
        #    renderedRelationshipDistance 2
        #    autoLayout
        #}
    }
}

```

**Comment by simonbrowndotje** [comment]
The [system context view](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#systemContext-view) lets you create a view for a specific software system, and people/software systems linked directly to it, so I'd recommend just using that:

```
        systemContext system {
            include *
            autolayout
        }
```

Alternatively, you could use a system landscape with an expression:

```
        systemlandscape {
            include ->system->
            autoLayout
        }
```

Alternatively still, you could write a script/plugin and use the underlying Java API to control which elements are added.

**Comment by cohen990** [comment]
ah the system landscape with an expression solves my problem, thank you!

Is there a place where I can browse plugins or anything like that?

**Comment by cohen990** [comment]
ok thank you for all your help! Shall I close the issue?

**Comment by WolframRatzke** [comment]
Hi, I have a similar question. The discussion above already helped me a lot. However, there is still one last step missing. Some Background:

We use C4 to model a system-of-systems that involves about 6+ different departments at our company. So, that approach is quite efficient when it comes to communication across all contributors. After identifiying all components, I would like to have a *very* complete overview. That means, showing *all* components simultanesouly  but also showing the boundaries for containers **and** systems. I made it work to include the boundaries for containers, see example code below. 

But is there a straight forward solution to also display the boundaries of the systems as lines as well?

    workspace {
    
        model {
            softwareSystem_A = softwareSystem "Software System A" "My software system A." {
                cont_A1 = container "Container A 1" {
                    comp_A1a = component "Component A 1 a"
                    comp_A1b = component "Component A 1 b"
                }
                cont_A2 = container "Container A 2"  {
                    comp_A2a = component "Component A 2 a"
                    comp_A2b = component "Component A 2 b"
                }
            }
            
            softwareSystem_B = softwareSystem "Software System B" "My software system B." {
                cont_B1 = container "Container B 1" {
                    comp_B1a = component "Component B 1 a"
                    comp_B1b = component "Component B 1 b"
                }
                cont_B2 = container "Container B 2"  {
                }
                
            }
            
    #Relations
            comp_A1a -> comp_A1b "relation"
            comp_A2a -> comp_A2b "relation"
            comp_A2b -> comp_A1a
            
            comp_B1a -> comp_B1b "relation"
            cont_B2 -> comp_A2b "relation"
            
            comp_B1a -> comp_A2b "relation"
            
        }
    
        views {
            #this view can be ignored
            container softwareSystem_A {
                include element.tag==Container
                include element.tag==Element
                #autoLayout
            }
            #the relevant view
            component cont_A1 { 
                #whereas cont_A1 could be any container
                include element.tag==Component
                include element.tag==Container
                #autoLayout
            }
        
            styles {
                theme default
                relationship "Relationship" {
                    color #333333
                    fontSize 25
                    thickness 3
                }
            }
        }

**Result of above model**

![Result of above model](https://user-images.githubusercontent.com/104376392/217200106-76f9e2ec-2caa-489a-8e57-254b2abb4354.png)

**Envisoned result with drawn system boundaries**

![Envisoned result with drawn system boundaries](https://user-images.githubusercontent.com/104376392/217200124-975c2ce7-f14c-4ede-a2d6-2d547bec3cb6.png)

Thanks a lot in advance
-Wolfram

**Comment by simonbrowndotje** [comment]
@WolframRatzke ... this is a closed issue - please open a new issue or discussion.
