### ISSUE TITLE
multiple instances in deployment

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#184]
I want to propose to be able to specify `many` or `N` as the argument of `instances`.

**Comment by dgutson** [comment]
This is more relevant when the instances are auto-scalable.

**Comment by simonbrowndotje** [comment]
Closing - duplicate of https://github.com/structurizr/structurizr/issues/106

**Comment by simonbrowndotje** [comment]
This is now available, and here are some examples:

`instances 3` -- the existing supported value
`instances 0..5` -- a range with a bounded upper limit
`instances 2..N` or `instances 2..*` -- a range with an unbounded upper limit

**Comment by dgutson** [comment]
Thanks!
