### ISSUE TITLE
Please allow to provide a description to the deploymentEnvironment

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#186]
Please allow this:

```
workspace {
    model {
        deploymentEnvironment singleNode {
            description "This is the case when the X and Y live in the same node"
         }
    }
}
```

and, equivalently, in the same declaration line:

```
workspace {
    model {
        deploymentEnvironment singleNode "This is the case when the X and Y live in the same node" {

         }
    }
}
```

BTW, it would be good if `tags` would also be supported as well.

**Comment by dgutson** [comment]
Ping

**Comment by simonbrowndotje** [comment]
"deployment environment" is just a string field in the underlying Java object model -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/DeploymentElement.java#L38 ... for reasons of backwards compatibility with earlier versions of the Java library. If I was designing the object model again, I'd certainly make deployment environment a first class citizen so it could support things like descriptions and properties. But it's not a straightforward change unfortunately. If you'd like to sponsor this from a financial point of view, please do let me know and I'll fast-track it.

**Comment by dgutson** [comment]
Let me see if @qequ can do it.

**Comment by dgutson** [comment]
Sorry, just checked. It extends Element which already has the description attribute. Why it can't be used?

**Comment by simonbrowndotje** [comment]
> Let me see if @qequ can do it.

Sure, no problem ... closing this issue then.

**Comment by dgutson** [comment]
Could you pls leave this open and assign to @jukMR?

**Comment by JukMR** [comment]
Hi! I confirm that I'm willing to work on this and solve this issue
