### ISSUE TITLE
Feature Request: Add ability to style group & enterprise outlines

### ISSUE THREAD

**Issue by AlexChesser** [structurizr/dsl#189]
Currently I have a diagram with multiple groups in an enterprise.  I personally find it very difficult to see the dotted outlines for group level styles.  They soft grey on white is nearly impossible for me to see.

As an accessibility and branding feature I'd love it if we had the ability to both style our group outlines under different colours so the groups are both more visible overall (maybe a higher opacity) and can have an outline with semantic meaning.

Maybe groups the ability to tag groups could solve this?

```
workspace "foo" {
   model {
      enterprise "bar" {
         group "GroupA" {
            A = softwaresystem "Software System A"
         }
         group "GroupB" {
            B = softwaresystem "Software System B"
         }
      }
   }
   views {
      styles {
         # maybe instead of "element" this reads "group GroupA" tag in the style
         element "GroupA" {
            # modifies the outline style of the group
            stroke #FF0000
         }
         element "GroupB" {
            stroke #00FF00
         }
         #maybe instead of element this reads "enterprise"
         element "bar" {
           stroke #0000FF 
         }
      }
   }
}
 ```

**Comment by simonbrowndotje** [comment]
Styling for boundaries and groups is already available; see https://structurizr.com/help/notation for details.
