### ISSUE TITLE
Allow styles for groups

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#197]
Please allow styles for groups. This is specially useful for multi-container applications grouped in groups, nested under software systems.

**Comment by dgutson** [comment]
In the language reference I didn't see groups can have tags and therefore cannot be referenced in the styles block.

**Comment by dgutson** [comment]
(documenting for other users)
After some attempts, I came up with this:
```
workspace {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            group "grp" {
                webapp = container "Web Application" {
                    user -> this "Uses"
                }
                container "Database" {
                    webapp -> this "Reads from and writes to"
                }
            }
        }
    }

    views {
        styles {
            element "Group:grp" {
                color #ff0000
                width 5
                border solid
            }
        }
        systemContext softwareSystem {
            include *
            autolayout lr
        }

        container softwareSystem {
            include *
            autolayout lr
        }

        theme default
    }
}
```

The only honored style attribute is the `color`; `width` and `border` are not.

I suggest:
* To add this information to the dsl/language-reference, so it is the single source of true.
* To enable tags to groups in order to turn the styling definition homogenic. This is counter-intuitive
* To enable other attributes

I propose to use this issue to at least address the documentation part.

**Comment by simonbrowndotje** [comment]
I've added a cookbook entry for groups -> https://github.com/structurizr/dsl/tree/master/docs/cookbook/groups

**Comment by dgutson** [comment]
With all due respect Simon, and I already demonstrated that I'm a big fan of c4 and structurizr, I think that the documentation is too spread. Personally, I ise the language reference, which as the name says, it should be a biblic-like source where everything else is based on. Currently, I see that i need to read too many places to have the full picture. There is no even a single (unique) table of contents or reading roadmap.
My suggestion is: keep something as a single source of truth (ie the language reference), complete, maybe not deep, but complete, and with reference from there to other documents, so people knows that it is the starting point.
Otherwise, we users don't know where to start from, cookbook, language reference, structurizr.com, examples, other linked (child) webpages.
It might be very obvious for you but please believe me that it is very puzzling for the users.
