### ISSUE TITLE
What model elements can be imported via !include keyword

### ISSUE THREAD

**Issue by torsten-systemticks** [structurizr/dsl#20]
I am still working on a VS Code extension and completing a corresponding Xtext Grammar for the DSL.

The **!include** feature is not yet implemented, but I want to do that soon.

Are there any rules/conventions what kind of model elements/fragments can be outsourced into files, which then can be imported with the !include keyword?

I found the one example

```
user = person "User" "A user of my software system."
softwareSystem = softwareSystem "Software System" "My software system."

user -> softwareSystem "Uses"
```

Is that the complete list? Persons, Software Systems (and sub-elements) and Relationships ?

Thanks,
Torsten

**Comment by simonbrowndotje** [comment]
The short answer is that an included file can have any elements that are valid within the included context. And included files can use `!include` too. So you could do:

```
workspace {
  !include model.dsl
  !include views.dsl
}
```

And `model.dsl` could be:

```
softwaresystem "A"
softwaresystem "B"
softwaresystem "C"

!include more-software-systems.dsl
```

And so on.

**Comment by torsten-systemticks** [comment]
Ah, got it, thanks.

I have overseen this comment in the docs:

_The content of any included files is simply inlined into the parent document._

This will be tricky to find an appropriate xtext solution for it.
I think this issue can be closed then.
