### ISSUE TITLE
Complete Overview of all Components with Containers and Systems Boundaries

### ISSUE THREAD

**Issue by WolframRatzke** [structurizr/dsl#209]
Hi,
we use C4 to model a system-of-systems that involves about 6+ different departments at our company. So, that approach is quite efficient when it comes to communication across all contributors. After identifiying all components, I would like to have a very complete overview. That means, showing all components simultanesouly but also showing the boundaries for containers and systems. I made it work to include the boundaries for containers, see example code below.

But is there a straight forward solution to also display the boundaries of the systems as lines as well?

    workspace {
    
        model {
            softwareSystem_A = softwareSystem "Software System A" "My software system A." {
                cont_A1 = container "Container A 1" {
                    comp_A1a = component "Component A 1 a"
                    comp_A1b = component "Component A 1 b"
                }
                cont_A2 = container "Container A 2"  {
                    comp_A2a = component "Component A 2 a"
                    comp_A2b = component "Component A 2 b"
                }
            }
            
            softwareSystem_B = softwareSystem "Software System B" "My software system B." {
                cont_B1 = container "Container B 1" {
                    comp_B1a = component "Component B 1 a"
                    comp_B1b = component "Component B 1 b"
                }
                cont_B2 = container "Container B 2"  {
                }
                
            }
            
    #Relations
            comp_A1a -> comp_A1b "relation"
            comp_A2a -> comp_A2b "relation"
            comp_A2b -> comp_A1a
            
            comp_B1a -> comp_B1b "relation"
            cont_B2 -> comp_A2b "relation"
            
            comp_B1a -> comp_A2b "relation"
            
        }
    
        views {
            #this view can be ignored
            container softwareSystem_A {
                include element.tag==Container
                include element.tag==Element
                #autoLayout
            }
            #the relevant view
            component cont_A1 { 
                #whereas cont_A1 could be any container
                include element.tag==Component
                include element.tag==Container
                #the order of the two lines above matters!
                #autoLayout
            }
        
            styles {
                theme default
                relationship "Relationship" {
                    color #333333
                    fontSize 25
                    thickness 3
                }
            }
        }
**Result from model above**
![components_View](https://user-images.githubusercontent.com/104376392/217204863-8a5f335e-fe2b-412f-9be3-e8a7f551526f.png)

**Envisoned result with drawn System boundaries**
![components-system_View](https://user-images.githubusercontent.com/104376392/217204882-718447fd-c8a4-468a-bef8-557aae48e227.png)

Thanks a lot in advance
-Wolfram

**Comment by simonbrowndotje** [comment]
This isn't supported, at least by the browser-based Structurizr renderer. That said, I can't imagine a diagram showing all components across multiple containers and software systems being anything but cluttered ... unless the containers you are modelling are *very* small?

**Comment by WolframRatzke** [comment]
_...unless the containers you are modelling are very small?_
Yes and no. We have one central Container which comprises many Components, which connect different other Systems (and Components in there, respectively) via different technologies. The other containers are quite small. 
As different teams are responsible for different components and the interfaces between them, I actually need both: High resolution (Component View) but also the assignment to the parent System for a clear understanding of the whole system and the end-to-end flow of signals, including their conversions.

Thinking in the analogy of maps, I would see it like a hiking map: 
If you use a digital map (on a navigation system, mobile phone) for hiking, you always have to struggle with either having an overview of the big mountains, but not seeing the small paths connecting them, or when zoomed in, seeing the small paths but losing the overview were they lead to and where they come from which makes it difficult to navigate on big routes.

Instead of having a digital map where you can digitally zoom-in/out, I see it like an old-fashioned analog hiking map where you have both: resolution and overview. If you need the overview, you make one step back and you can see the whole alps. And if you need details, the small paths you must walk to get from one mountain to another one, you put your head closer to the map and follow that small lines, but still having the big picture.

My demand is like an analog hiking map, resolution and overview in one. I would not bother if I have to scroll a lot, use a 4K projector, or to print it on a A0 paper (literally analog) :)

Just as an idea. 
Anyway, many thanks for that great tool! :)

**Comment by simonbrowndotje** [comment]
Thanks! Closing as not planned, but it may be added in the future.
