### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by torsten-systemticks** [structurizr/dsl#22]
There are missing dependencies, when building the project with gradle, like:

import com.structurizr.documentation.AdrToolsImporter;
                                    ^
  symbol:   class AdrToolsImporter
  location: package com.structurizr.documentation
C:\development\projects\dsl\src\main\java\com\structurizr\dsl\AdrsParser.java:39: error: cannot find symbol
            AdrToolsImporter adrToolsImporter = new AdrToolsImporter(workspace, path);
            ^

**Comment by simonbrowndotje** [comment]
This should be all fixed now.
