### ISSUE TITLE
Allow styles defined in an extending workspace to override those in the base workspace

### ISSUE THREAD

**Issue by iambic69** [structurizr/dsl#241]
### Description

Using the 'workspace extends' feature, I'd like to be able to define styles in the base workspace, but then override them in extending workspaces.  Currently this fails when `com.structurizr.view.Styles#add(com.structurizr.view.ElementStyle)` throws an `IllegalArgumentException` (An element style for the tag "..." already exists.)  Is there any reason we couldn't change that behaviour to allow element styles encountered later during DSL parsing to update/replace the earlier definition?

Themes are more flexible, of course, but they have to be loaded from an HTTP URL.  I'd like to work just with styles in the DSL files.

### Priority

Medium

### Resolution

I'm willing to add this feature myself and raise a PR

**Comment by simonbrowndotje** [comment]
Issue moved, as this was an easy addition to the DSL library.

**Comment by iambic69** [comment]
Thanks @simonbrowndotje, but I think that's just going to cause subsequent re-definition of an element style to be ignored, rather than throw an exception, isn't it?  What I'd ideally like to see is the opposite (and more sophisticated) behaviour: subsequent element styles get _merged_ with and override earlier ones.

**Comment by simonbrowndotje** [comment]
> that's just going to cause subsequent re-definition of an element style to be ignored, rather than throw an exception, isn't it?

It shouldn't - take a look at the test cases I added in that commit.

**Comment by simonbrowndotje** [comment]
Screenshot of the new change in action...

<img width="1728" alt="Screenshot 2023-04-02 at 10 56 51" src="https://user-images.githubusercontent.com/1009874/229345835-0326138b-62a0-4f71-a89c-df16b5756093.png">

**Comment by iambic69** [comment]
Sorry @simonbrowndotje, I probably took too cursory a look. I'll look again in the morning. Tucked up in bed here in NZ!

**Comment by iambic69** [comment]
Fantastic!

Thanks for making that change so swiftly.  It'll be really valuable for the Enterprise-wide, 'workspace extends' scenario.

Andrew
