### ISSUE TITLE
Group Text fontSize and location

### ISSUE THREAD

**Issue by ammarck** [structurizr/dsl#248]
### Description

I have a system context diagram where we have groups and I wanted to make the group more clear by increasing the text size and maybe the group name top left (since I am putting it on a doc and people read from top to bottom when they scroll). However, AFAIK there isn't a way in the DSL to change these two properties in groups. The only thing that can be modified is icon and color

### Priority

Low

### Resolution

I'm willing to sponsor/donate to this feature (add details below)

**Comment by simonbrowndotje** [comment]
Changing the font size for groups is already supported -> https://structurizr.com/help/notation#elements

Example:
```
workspace {

    model {
        group "Group 1" {
            person "User 1"
        }
        group "Group 2" {
            person "User 2"
        }
    }

    views {
        systemLandscape {
            include *
            autoLayout
        }

        styles {
            element "Group:Group 1" {
                fontsize 40
            }
        }
    }

}
```

![image](https://user-images.githubusercontent.com/1009874/236128296-2f079e4c-5add-40f1-889e-89b236a95ed5.png)

Changing the location isn't supported though.

**Comment by goto1134** [comment]
@simonbrowndotje , do the diagram exporters support these properties?

**Comment by ammarck** [comment]
@simonbrowndotje that worked thanks!
