### ISSUE TITLE
Inconsistency between language reference and Big Bank PLC example for relationships in deploymentEnvironment

### ISSUE THREAD

**Issue by yt-ms** [structurizr/dsl#26]
I've noticed an inconsistency between the [language reference](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md) and the [Big Bank PLC example](https://github.com/structurizr/dsl/blob/master/examples/big-bank-plc.dsl).  The example has a relationship (`primaryDatabaseServer -> secondaryDatabaseServer "Replicates data to"`) within a `deploymentEnvironment` where this is not supported according to the language reference.

Could one or other be updated so they match please?

**Comment by simonbrowndotje** [comment]
The [relationship section](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#relationship) indicates that deployment node to deployment node relationships are supported. It's the fact that relationship is defined inside the `deploymentEnvironment` block that's missing from the language reference?

**Comment by yt-ms** [comment]
Yep, exactly.  Not a major issue, but it'd be good to correct the language reference if that is supported.
