### ISSUE TITLE
Add escape sequence for double quotes

### ISSUE THREAD

**Issue by toorog** [structurizr/dsl#29]
Any property containing `"` ends up producing the error message `com.structurizr.dsl.StructurizrDslParserException: Expected: <name> <value> at line 10: myproperty "This is an \"example\""`

Example:
```
properties {
    myproperty "This is an \"example\""
}
```

We need a way to escape double quotes. A backslash does obviously not work currently.

Background: We use properties to attach structured data (JSON format) to model elements. JSON requires to use doublequotes for fields.

**Comment by simonbrowndotje** [comment]
This was actually on my todo list. 🙂 The [DSL demo](https://structurizr.com/dsl) is now using this updated version of the DSL parser - could you take a look and see if it works for you?

**Comment by toorog** [comment]
LGTM. A quick test succeeded.

**Comment by simonbrowndotje** [comment]
That's great, thanks!
