### ISSUE TITLE
Predefined tags of elements not described in the language reference

### ISSUE THREAD

**Issue by gilbertotcc** [structurizr/dsl#3]
According to the documentation in *Language reference*, the element styles are defined using tags as identifiers (see [element style](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#element-style)). Although this is true, in my opinion documentation should specify that elements have predefined tags (e.g. *Element* and *Person* for persons).

I can create a pull request to add this information if you think it can improve the documentation.

**Comment by simonbrowndotje** [comment]
Thanks, I've added more information about tags.
