### ISSUE TITLE
Add elements to a view based upon tag(s)

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#35]
Hello,

I tried to generate some filtered views based on tags for a more complex view. Even though the elements are filtered properly, the diagram generated with autoLayout doesn't look good: looks like it firstly generate the complex diagram with all elements with autolayout, and then show/hide the elements with the specified tags. As a result, the elements are not distributed properly. I would like to first filter elements and then apply the autolayout, so the diagram would look better.

I created a sample DSL code to help me on explaining the issue so you can also reproduce it.

I have a container diagram like this (see #All_Containers):
![image](https://user-images.githubusercontent.com/11686949/108574692-5c4ea780-7318-11eb-8cf4-92b3b92cad45.png)

Then I create two filtered views, generating the following diagrams:

#All_Containers_tag1:
![image](https://user-images.githubusercontent.com/11686949/108574858-b8193080-7318-11eb-9b9e-da77f5f7252d.png)

#All_Containers_tag2:
![image](https://user-images.githubusercontent.com/11686949/108574896-d3843b80-7318-11eb-9d78-3f21578cfc0c.png)

I would like them to be generated in this way:
#All_Containers_tag1_expectation:
![image](https://user-images.githubusercontent.com/11686949/108575048-50171a00-7319-11eb-81c9-cbe5672d9906.png)

#All_Containers_tag2_expectation:
![image](https://user-images.githubusercontent.com/11686949/108575067-5f966300-7319-11eb-8c39-2f299b74fa8c.png)

If there is any way to achive my goal, let me know.

Thanks for your support.

Sample DSL:
```
workspace "Amazon Web Services Example" "An example AWS deployment architecture." {
    model {
        springPetClinic = softwaresystem "Spring PetClinic" "Allows employees to view and manage information regarding the veterinarians, the clients, and their pets." "Spring Boot Application"{
            app = container "Mobile App" "Show information regarding the veterinarians, the clients, and their pets." "android" "Mobile App, tag1, tag2"
            api1 = container "API 1" "API 2" "Java and Spring Boot" "tag1"
            api2 = container "API 2" "API 2" "Java and Spring Boot" "tag2"
            database = container "Database" "Stores information regarding the veterinarians, the clients, and their pets." "Relational database schema" "Database, tag1"
        }
        thirdPartyApi1 = softwaresystem "Third-Party API 1" "" "tag1"
        thirdPartyApi2 = softwaresystem "Third-Party API 2" "" "tag2"
        
        app -> api1 "manages data" "AWS API Gateway" "tag1"
        app -> api2 "manages data" "AWS API Gateway" "tag2"
        api1 -> database "Reads from and writes to" "JDBC/SSL" "tag1"
        api1 -> thirdPartyApi1 "Get 3rd pary data" "HTTP" "tag1"
        api2 -> thirdPartyApi2 "Get 3rd pary data" "HTTP" "tag2"

        
    }
         
    views {
        container springPetClinic "All_Containers" {
            include *
            autoLayout
        }
        
        container springPetClinic "All_Containers_tag1_expectation" {
            include app api1 database thirdPartyApi1
            autoLayout
        }
        
        container springPetClinic "All_Containers_tag2_expectation" {
            include app api2 thirdPartyApi2
            autoLayout
        }
        
        filtered All_Containers include "tag1, tag2" "All_Containers_tag1_tag2"
        filtered All_Containers include "tag1" "All_Containers_tag1"
        filtered All_Containers include "tag2" "All_Containers_tag2"
        

        styles {
            element "Element" {
                shape roundedbox
                background "#ffffff"
            }
            element "Database" {
                shape cylinder
            }
            element "Mobile App" {
                shape MobileDeviceLandscape
            }
            element "Infrastructure Node" {
                shape roundedbox
            }
        }

        themes https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json
    }
}
```

**Comment by simonbrowndotje** [comment]
That's the intended behaviour. From https://structurizr.com/help/filtered-views:

> The benefit of using filtered views is that element and relationship positions are shared between the filtered views.

Filtered views are designed to share the same underlying layout, so that they can be easily compared side-by-side (e.g. before and after, current and future state, etc).

**Comment by juanrferia** [comment]
Thanks for the clarification. Then, is there any way to get the view I want based con element tags?

**Comment by simonbrowndotje** [comment]
Not with tags, I'm afraid.

**Comment by simonbrowndotje** [comment]
It should be possible to add a feature to do something like this though:

```
container springPetClinic {
    include "tag:tag 1"
    autoLayout
 }
```

**Comment by juanrferia** [comment]
That feature would be great! I would suggest it supporting multiple tags. Thanks

**Comment by simonbrowndotje** [comment]
I think I'd like to do something like this:

- include elements that have the specified tag: `include "tag:tag 1"`
- include elements that have all of the specified tags: `include "tag:tag 1,tag 2"`

So these two blocks would potentially yield different results:

```
container springPetClinic {
    include "tag:tag 1"
    include "tag:tag 2"
    autoLayout
 }
```

```
container springPetClinic {
    include "tag:tag 1,tag 2"
    autoLayout
 }
```

Thoughts?

**Comment by juanrferia** [comment]
Sounds great. So, the first example would include all elements with tag tag1 or tag2, while the second example would include all elements having both tag1 and tag2. Right?

**Comment by simonbrowndotje** [comment]
Correct, yes ... with your examples, something like this:

```
container springPetClinic "All_Containers_tag1_expectation" {
    include "element.tag=tag1"
    autoLayout
}

container springPetClinic "All_Containers_tag2_expectation" {
    include "element.tag=tag2"
    autoLayout
}
```

I'm thinking that a syntax of `element.tag=` allows for similar features in the future, perhaps `relationship.tag=`, or `element.property.name=value` (somebody was asking about this recently).

**Comment by juanrferia** [comment]
Awesome! Thanks

**Comment by simonbrowndotje** [comment]
This is now available to try at [https://structurizr.com/dsl](https://structurizr.com/dsl):

```
workspace "Amazon Web Services Example" "An example AWS deployment architecture." {
    model {
        springPetClinic = softwaresystem "Spring PetClinic" "Allows employees to view and manage information regarding the veterinarians, the clients, and their pets." "Spring Boot Application"{
            app = container "Mobile App" "Show information regarding the veterinarians, the clients, and their pets." "android" "Mobile App, tag1, tag2"
            api1 = container "API 1" "API 2" "Java and Spring Boot" "tag1"
            api2 = container "API 2" "API 2" "Java and Spring Boot" "tag2"
            database = container "Database" "Stores information regarding the veterinarians, the clients, and their pets." "Relational database schema" "Database, tag1"
        }
        thirdPartyApi1 = softwaresystem "Third-Party API 1" "" "tag1"
        thirdPartyApi2 = softwaresystem "Third-Party API 2" "" "tag2"
        
        app -> api1 "manages data" "AWS API Gateway" "tag1"
        app -> api2 "manages data" "AWS API Gateway" "tag2"
        api1 -> database "Reads from and writes to" "JDBC/SSL" "tag1"
        api1 -> thirdPartyApi1 "Get 3rd pary data" "HTTP" "tag1"
        api2 -> thirdPartyApi2 "Get 3rd pary data" "HTTP" "tag2"
    }
         
    views {
        container springPetClinic "All_Containers_tag1_expectation1" {
            include app api1 database thirdPartyApi1
            autoLayout
        }
        
        container springPetClinic "All_Containers_tag2_expectation1" {
            include app api2 thirdPartyApi2
            autoLayout
        }
        
        container springPetClinic "All_Containers_tag1_expectation2" {
            include "element.tag==tag1"
            autoLayout
        }
        
        container springPetClinic "All_Containers_tag2_expectation2" {
            include "element.tag==tag2"
            autoLayout
        }
        
        styles {
            element "Element" {
                shape roundedbox
                background "#ffffff"
            }
            element "Database" {
                shape cylinder
            }
            element "Mobile App" {
                shape MobileDeviceLandscape
            }
            element "Infrastructure Node" {
                shape roundedbox
            }
        }

        themes https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json
    }
}
```

**Comment by juanrferia** [comment]
Nice! Thanks for implementing it so fast. Quick one: in case I want to pick both elements and relationships with the same tag 'tag1', should I use "tag==tag1" directly?

**Comment by simonbrowndotje** [comment]
Probably not. For convenience, whenever you add an element to a view, any relationships from/to that element are also added to the view. So you're probably going to end up doing something like this:

```
include "element.tag==tag1"
exclude "* -> *"
include "relationship.tag==tag1"
```

I'll push another version up to the demo page once the `relationship.tag==` expression is supported.

**Comment by simonbrowndotje** [comment]
That's now available ... this will work:

```
        container springPetClinic "All_Containers_tag1_expectation2" {
            include "element.tag==tag1"
            exclude * -> *
            include "relationship.tag==tag1"
            autoLayout
        }
```

**Comment by juanrferia** [comment]
Is this feature also supported in deployment views?

**Comment by simonbrowndotje** [comment]
It hopefully will be, although it requires a little more thought based upon the way that the current implementation of `include` for deployment views works (it expects deployment nodes).

**Comment by simonbrowndotje** [comment]
[This commit](https://github.com/structurizr/dsl/commit/9b140f44adc0d2a8b3632d6dba6dd30c6cc60be8) adds support for static views.

**Comment by juanrferia** [comment]
Cool! It is not live yet, right? I was trying including/excluing via relationship tags

**Comment by simonbrowndotje** [comment]
Correct, it's only available on the demo page at the moment - there should be a new CLI release in the next week or so.

**Comment by dgradl-fl** [comment]
When is this release expected?

**Comment by simonbrowndotje** [comment]
Hopefully next week.

**Comment by simonbrowndotje** [comment]
CLI v1.9.0 is now available -> https://github.com/structurizr/cli/releases/tag/v1.9.0

(the tags functionality still isn't implemented for deployment views, but this will follow)

**Comment by MTomBosch** [comment]
Is the tag support available for dynamic views?

**Comment by simonbrowndotje** [comment]
It's not ... since you're adding *instances* of relationships from the static model in a specific order, I'm not sure that adding relationships based upon tags is very useful.

**Comment by juanrferia** [comment]
Hi Simon, do you have a ticket for enabling this feature in deployment views? If not, can you share the status? Thank you!

**Comment by simonbrowndotje** [comment]
I stashed the code to release support for static views, but an initial version is running at [https://structurizr.com/dsl](https://structurizr.com/dsl) ... let me know what you think.

**Comment by MTomBosch** [comment]
> 
> 
> It's not ... since you're adding _instances_ of relationships from the static model in a specific order, I'm not sure that adding relationships based upon tags is very useful.

Yes, you are right. Since I am anyway controlling via the relations which elements are shown the inclusion via tags makes no sense at all :)

**Comment by juanrferia** [comment]
> I stashed the code to release support for static views, but an initial version is running at https://structurizr.com/dsl ... let me know what you think.

Almost perfect! Including elements by tag is working, but I cannot include relationship by tags. Can you check? Thanks!

**Comment by simonbrowndotje** [comment]
Unfortunately it's not almost perfect ... on writing the unit tests, I found the initial version of `include element.tag==X` support for deployment views didn't work in all situations. For example, the previous expression could be interpreted to include:

- software system instances that have a tag of X
- instances of software systems that have a tag of X

These are very different, and there's no way to distinguish what the user was really looking for. So I've made some enhancements. By default, `include element.tag==X` will include both the cases above, as I think this is more likely the functionality that people would expect.

But you can override it by specifying the type of the element you're interested in, for example:

- `include "element.type==Container && element.tag==X"`
- `include "element.type==ContainerInstance && element.tag==X"`

This is running at [https://structurizr.com/dsl](https://structurizr.com/dsl) ... please take a look and let me know if it still works for you.

**Comment by simonbrowndotje** [comment]
I've added support for including relationships by tag now too, with the following DSL definition as an example:

```
workspace {

    model {
        softwareSystem = softwaresystem "Software System" {
            webApplication = container "Web Application" 
            database = container "Database"
        }

        webApplication -> database "Reads from and writes to" "JDBC/SSL" "Tag 1"

        deploymentEnvironment "Live" {
            deploymentNode "Amazon Web Services" {
                route53 = infrastructureNode "Route 53"
                elb = infrastructureNode "Elastic Load Balancer"
                deploymentNode "EC2" {
                    webApplicationInstance = containerInstance webApplication
                    containerInstance database
                }

                route53 -> elb "Forwards requests to" "HTTPS" "Tag 2"
                elb -> webApplicationInstance "Forwards requests to" "HTTPS" "Tag 3"
            }
        }
    }
         
    views {
        deployment * "Live" {
            include "element.type==InfrastructureNode"
            include "element.tag==Container Instance"
            exclude * -> *
            include "relationship.tag==Tag 1"
            include "relationship.tag==Tag 2"
            include "relationship.tag==Tag 3"
            autolayout lr
        }
   }
   
}
```

Does that work as you'd expect? Also, what's your use case for including relationships by tag?

**Comment by juanrferia** [comment]
Hi Simon. Looks great! 
My usecase for including relationships: I found some of my deployment diagrams difficult to read beacuse they included too many relationships. I decided to hide all relationships between containers and systems and, instead, I created just a few simple relationships bettween deployments nodes to represent them as an abstaction and make it clear.
Thanks a lot!

**Comment by AndreiPashkin-SoftTeco** [comment]
For future readers - syntax has changed, now you have to write `exclude "* -> *"` and not `exclude * -> *`.

**Comment by AndreiPashkin** [comment]
For future readers - syntax has changed, now you have to write `exclude "* -> *"` and not `exclude * -> *`.
