### ISSUE TITLE
People and software systems are never marked as "external"

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/dsl#37]
External systems are styled the same way like internal systems.
Looking at the generated puml file the external systems are defined as regular "system" items although it should be "external_system".

I am using 1.8.1.

**Comment by apoorva-sriv** [comment]
Could you please provide an example of how to mark a system as external in a system context diagram without using `enterprise`?

**Comment by simonbrowndotje** [comment]
If an enterprise is specified, all software systems outside of this are marked as external automatically; see https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/ModelDslContext.java#L17

**Comment by apoorva-sriv** [comment]
> If an enterprise is specified, all software systems outside of this are marked as external automatically; see https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/ModelDslContext.java#L17

I do not want to use `enterprise` since the other systems are also in the same enterprise.

**Comment by simonbrowndotje** [comment]
C4-PlantUML's `System_Ext` renders the software system in a different colour. If that's what you're trying to do, I'd recommend just tagging the software system and creating an element style that specifies a different background colour.
