### ISSUE TITLE
Relationships to/from instances not working

### ISSUE THREAD

**Issue by toorog** [structurizr/dsl#39]
The documentation describes that relations
- from `Software System Instance` to `Infrastructure Node, Software System Instance, Container Instance`
- from `Container Instance` to `Infrastructure Node, Software System Instance, Container Instance`

are allowed. However, when creating any relation between ContainerInstance or SoftwareSystemInstance to one of the other elemens listed as valid, I get an error message that the relation is not allowed.

At a first glance the problem seems to be burried in [AbstractRelationshipParser.java](https://github.com/structurizr/dsl/blob/ebb951ae9c738619289e2a629ccd62718878e789/src/main/java/com/structurizr/dsl/AbstractRelationshipParser.java) which IMHO doesn't include if conditions to allow the relations listed above.

Example:
```
workspace "Getting Started" "This is a model of my software system." {

    model {
        ss1 = softwareSystem "Software System" "My software system." {
            cont1 = container "Container" "Container"
        }
        
        ss2 = softwareSystem "Software System 2" ""

        
        deploymentEnvironment "deploytest" {
            deploymentNode wrapper "Wrapper" "Wrapper" {
                ssinstance = softwareSystemInstance ss2
                
            }
            deploymentNode wrapper2 "Wrapper2" "Wrapper" {
                continst = containerInstance cont1
                continst -> ssinstance "connects" ""
            }
        }
    }
    views {
        deployment * deploytest deploytest "test" {
            include *
        }
    }
}
```

Error Message: 
`A relationship between "ContainerInstance://deploytest/wrapper2/Software System.Container[1]" and "SoftwareSystemInstance://deploytest/wrapper/Software System 2[1]" is not permitted at line 22: continst -> ssinstance "connects" "" `

**Comment by simonbrowndotje** [comment]
Relationships between element instances are permitted in the deployment model, but they need to be created in the static model ... so you'll need to create a relationship between `cont1` and `ss2`.

![Screenshot 2021-02-24 at 18 55 06](https://user-images.githubusercontent.com/1009874/109050900-d644af00-76d1-11eb-8ca9-c9bd09e3f895.png)

**Comment by toorog** [comment]
Thanks for the quick reply. Since you also updated the documentation, I assume that links btw. Instances are not allowed at all. 

Unfortunately having relationships btw. static elements only does not solve the problem. Given the appended example, this would lead to all clients connecting to all servers. Whereas it should be like `clientInstance1 -connects-> serverInstance1` and `clientInstance2 -connects-> serverInstance2`.

Am I mistaken in the way how I am modelling this setup, or would the links btw. instances exactly what is required here?

```
workspace "Getting Started" "This is a model of my software system." {

    model {
        client = softwareSystem "Client" ""
        server = softwareSystem "Server" ""

        client -> server "connects" ""
        
        deploymentEnvironment "deploytest" {
            deploymentNode wrapper "Wrapper" "Wrapper" {
                clientInstance1 = softwareSystemInstance client
                clientInstance2 = softwareSystemInstance client
            }
            deploymentNode wrapper2 "Wrapper2" "Wrapper" {
                serverInstance1 = softwareSystemInstance server
                serverInstance2 = softwareSystemInstance server
            }
        }
    }
    views {
        deployment * deploytest deploytest "test" {
            include *
        }
    }
}
```

**Comment by simonbrowndotje** [comment]
You're welcome. What happens is that Java client library replicates all relationships between software system/container instances within the same deployment environment. So, for your example, it will lead to all clients connecting to all servers. One solution is to use separate deployment environments for each client-server pair ... the downside is that you can't show more than a single deployment environment on a deployment view.

Another option is an unreleased feature I have, which allows you to "group" software system/container instances, so that relationships are only replicated between software system/container instances in the same group. Here's a modified version of your example, where I've introduced `Service 1` and `Service 2` deployment groups:

```
workspace "Getting Started" "This is a model of my software system." {

    model {
        client = softwareSystem "Client" ""
        server = softwareSystem "Server" ""

        client -> server "connects" ""
        
        deploymentEnvironment "deploytest" {
            service1 = deploymentGroup "Service 1"
            service2 = deploymentGroup "Service 2"
            
            deploymentNode wrapper "Wrapper" "Wrapper" {
                clientInstance1 = softwareSystemInstance client service1
                clientInstance2 = softwareSystemInstance client service2
            }
            deploymentNode wrapper2 "Wrapper2" "Wrapper" {
                serverInstance1 = softwareSystemInstance server service1
                serverInstance2 = softwareSystemInstance server service2
            }
        }
    }
    views {
        deployment * deploytest deploytest "test" {
            include *
        }
    }
}
```

![Screenshot 2021-02-25 at 11 27 49](https://user-images.githubusercontent.com/1009874/109147732-43e9ed00-775d-11eb-9aa5-1d4edc2cc6f6.png)

I can deploy this to the https://structurizr.com/dsl demo page if you'd like to try it.

**Comment by toorog** [comment]
The group feature sounds great. I'd really like to try it. Looking forward to the next release of the CLI!

However, I still don't fully understand the reasoning why relationships between instances are not directly allowed. Seems pretty obvious to me that instantiated building blocks might have some relations that the static blocks don't have. Is there any reason (besides it is just not implemented currently)?

**Comment by simonbrowndotje** [comment]
> Seems pretty obvious to me that instantiated building blocks might have some relations that the static blocks don't have.

Do you have an example?

**Comment by donald-richardson-dxd** [comment]
> > Seems pretty obvious to me that instantiated building blocks might have some relations that the static blocks don't have.

> Do you have an example?

My example is that I have a software instance B that can be configured to retrieve or serve content from any software instance A like so A <- B <- A. However, without being able to specify instance relationships I will always get retrieve/serve for both relationships (A <--> B <--> A) and it doesn't make sense because the data is only flowing in one direction. And deployment groups do not fix this issue. The only thing I can do is two make two separate A's that look the same despite the fact that they are the same software instance.

**Comment by simonbrowndotje** [comment]
> My example is that I have a software instance B that can be configured to retrieve or serve content from any software instance A like so A <- B <- A. However, without being able to specify instance relationships I will always get retrieve/serve for both relationships (A <--> B <--> A) and it doesn't make sense because the data is only flowing in one direction. And deployment groups do not fix this issue. The only thing I can do is two make two separate A's that look the same despite the fact that they are the same software container.

Would the `exclude` feature work here?

```
workspace {

    model {
        a = softwareSystem "A"
        b = softwareSystem "B"
        
        a -> b "Sends to"
        b -> a "Sends to"
        
        live = deploymentEnvironment "Live" {
            deploymentNode "Server" {
                a1 = softwareSystemInstance a
                a2 = softwareSystemInstance a
                b1 = softwareSystemInstance b
            }
        }
        
    }
    
    views {
        deployment * live {
            include *
            exclude "a1 -> b1"
            exclude "b1 -> a2"
            autolayout
        }
    }
    
}
```

**Comment by donald-richardson-dxd** [comment]
I tried that and thought it didn't work; I'm using hierarchical identifiers. It turns out that I was using an alias like `live` but my view referred to the name "Live" so my identifiers namespaces were incorrect. This method does indeed resolve my issue. Thanks!
