### ISSUE TITLE
Relationship end styles is missing

### ISSUE THREAD

**Issue by davaya** [structurizr/dsl#40]
Relationships have semantics, the DSL doesn't have keywords for line ends (none, arrow, filled and unfilled circle, filled and unfilled triangle, filled and unfilled diamond) that are needed to show semantics like inheritance, aggregation, composition, etc.

(See https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/).

**Comment by simonbrowndotje** [comment]
That's correct - the Structurizr tooling doesn't support UML, and only supports a limited notation, as described at [Structurizr - Help - Notation](https://structurizr.com/help/notation).
