### ISSUE TITLE
Different behaviour dsl compared to code: multiple relationships definitions between same elements

### ISSUE THREAD

**Issue by lhohan-cb** [structurizr/dsl#41]
We recently converted from code to the DSL.

It seems there may be different behaviour when defining multiple relationships between the same elements.

For example for the DSL:

```
"a" -> "b" "text 1"
"a" -> "b" "text 2"
```

For the DSL this only draws a single line, with the first explanation, so `text 1`.
In code multiple lines would be drawn. (We used the Java client.)

Not sure if this is a bug or a feature of the DSL but we used these definitions regularly.

We can work around it by combining all texts on a single relationship but first feel is it more arrows is more clear than more text on single relationship.

**Comment by simonbrowndotje** [comment]
Do you have an example? This works for me:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses 1"
        user -> softwareSystem "Uses 2"
    }

}
```

![Screenshot 2021-03-03 at 20 51 48](https://user-images.githubusercontent.com/1009874/109870727-5e8efb00-7c62-11eb-87e3-5e2a2c00e4ee.png)

**Comment by lhohan-cb** [comment]
Thank you for your swift reply.

I must admit I am slightly confused (our model is quite big) on what worked in code before and what not.

It seems to be related to a container view of a software system where relationship are defined between the containers. 

```
workspace "Getting Started" "This is a model of my software system." {

    model {
        user = person "User" "A user of my software system."
        softwareSystem = softwareSystem "Software System" "My software system." {
            cA = container "A" "A"
        }
        softwareSystem1 = softwareSystem "Software System1" "My software system1." {
            cB = container "B" "B"
        }

        cA -> cB "text 1"
        cA -> cB "text 2"
    }

    views {
        container softwareSystem "containers" "containers" {
            include *
        }
    }
    
}
```

<img width="1897" alt="image" src="https://user-images.githubusercontent.com/53571103/109874684-baac4c00-7c6f-11eb-9c68-bcdb5283dd4a.png">

**Comment by lhohan-cb** [comment]
Thank you for the clear explanation and advice @simonbrowndotje .

I am not so sure anymore about the difference between the code and the DSL and giving you explanation if it is relevant.

I'll close the issue.

**Comment by lhauspie-adeo** [comment]
Sorry to answer a old and closed issue @simonbrowndotje but I'm interested to have all the relationships of containers in the SystemContext diagramm.

I understand your tips about modeling multiple relationships to simplify the overview but in some cases we need them all to exchange with another team about dependencies between our softwareSystem and their and we don't want to lose the other team's members with containers details.

In the [Java lib](https://github.com/structurizr/java/blob/master/docs/implied-relationships.md), it's possible to configure that to have or not the implied relationships. Why do you choosen to not do the same thing in the DSL ?

**Comment by simonbrowndotje** [comment]
You can disable the implied relationships functionality if needed, with [!impliedRelationships false](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#impliedRelationships). Is that what you're asking?

**Comment by lhauspie-adeo** [comment]
Not really, sorry my english is a bit rusty.
My point was:
With this Java Code
```java
        // a Structurizr workspace is the wrapper for a software architecture model, views and documentation
        Workspace workspace = new Workspace("Getting Started", "This is a model of my software system.");
        Model model = workspace.getModel();
/* NOTE HERE THE USAGE OF impliedRelationshipsStrategy */
        model.setImpliedRelationshipsStrategy(new CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy());

        // add some elements to your software architecture model
        SoftwareSystem softwareSystem = model.addSoftwareSystem(Location.Internal, "Software System", "My software system.");
        SoftwareSystem softwareSystem1 = model.addSoftwareSystem(Location.External, "Software System 1", "External software system.");

        Container container = softwareSystem.addContainer("Container", "Container");
        Component component = container.addComponent("Component", "Component");

        Container container1 = softwareSystem1.addContainer("Container 1", "Container 1");
        Component component1 = container1.addComponent("Component 1", "Component 1");

        component.uses(component1, "Sends data X to");
        component.uses(component1, "Sends data Y to");
```

Structurizer render this systemContext diagram (which contains both relationships):
![image](https://user-images.githubusercontent.com/52406406/157716395-2c3bcc8d-f21d-473c-973f-3f31d2669bdc.png)
If we remove the impliedRelationshipsStrategy from the model, the relationships desapear.

But I don't find any way to choose a impliedRelationshipsStrategy in the dsl.  
**Is there a particular reason to not allow this with the dsl ?**

Note that the same model with the dsl:
```
workspace "Getting Started" "This is a model of my software system." {
    !impliedRelationships true
    
    model {
        enterprise = enterprise "enterprise" {
            softwareSystem = softwareSystem "Software System" "My software system." {
                container = container "Container" "Container" {
                    component = component "Component" "Component"
                }
            }
        }
        softwareSystem1 = softwareSystem "Software System 1" "External software system." {
            container1 = container "Container 1" "Container 1" {
                component1 = component "Component 1" "Component 1"
            }
        }

        component -> component1 "Sends data X to"
        component -> component1 "Sends data Y to"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }
    }
}
```
Structurizr render this diagram:
![image](https://user-images.githubusercontent.com/52406406/157718729-c15d44f0-dac6-49d8-869c-049c6beb816b.png)


Maybe this feature could interest some other architects:
```
    !impliedRelationships < false | default | createImpliedRelationshipsUnlessAnyRelationshipExists | createImpliedRelationshipsUnlessSameRelationshipExists >
```
Or something like that.

**Comment by simonbrowndotje** [comment]
The DSL is a wrapper for the Java library, so you can do that via a script if you're using Structurizr Lite/CLI:

```
workspace "Getting Started" "This is a model of my software system." {
    
    !script groovy {
        workspace.getModel().setImpliedRelationshipsStrategy(new com.structurizr.model.CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy());
    }
    
    model {
        enterprise = enterprise "enterprise" {
            softwareSystem = softwareSystem "Software System" "My software system." {
                container = container "Container" "Container" {
                    component = component "Component" "Component"
                }
            }
        }
        softwareSystem1 = softwareSystem "Software System 1" "External software system." {
            container1 = container "Container 1" "Container 1" {
                component1 = component "Component 1" "Component 1"
            }
        }

        component -> component1 "Sends data X to"
        component -> component1 "Sends data Y to"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }
    }
}
```

**Comment by lhauspie-adeo** [comment]
Thanks for your quick replies, your time and your help.
It works with Structurizr Lite.

It was the last blocking point to adopt C4 DSL in our team.
🙏 Thanks again.
