### ISSUE TITLE
Defining styles resets complete default structurizr style

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/dsl#42]
I really like the default styling when exporting a dsl file to structurizr plantuml format. What I would like to do now is to easily add icons for certain element types (tags) but keep the rest. Using styles and the themes (did not try it yet) I can easily add icons and other style information.

But when styles is being used in a dsl then automatically all styling is gone/reset. My proposal would be that there should be a switch whether using styles in a dsl resets the complete styling or the given default styles should just override the specific style settings.

As a workaround getting the complete default styling to be added to the dsl and changing it where required would also be fine.

**Comment by simonbrowndotje** [comment]
Yes, the default styles are only added to the workspace when no styles are present. The set of default styles are listed here though, so you can easily add them into your DSL file -> https://github.com/structurizr/cli/blob/master/docs/defaults.md#styles

The [theme support](https://structurizr.com/help/themes) in the Structurizr render allows you to define a basic set of styles as a theme, and override them at the workspace level ... but I have a feeling that it doesn't work like that for the PlantUML exports.

**Comment by MTomBosch** [comment]
Thanks for the fast answer. I still do have two small questions and then we could also close this issue from my point of view since the workaround is really simple. 

1. Regarding themes: When you say "override" you mean the complete style of the related element is overwritten or just the part that has been defined in the workspace?
2. "but I have a feeling that it doesn't work like that for the PlantUML exports." You mean all of the Plantuml formats including the default plantuml/structurizr format? This only works when uploading to the structurizr server?

**Comment by simonbrowndotje** [comment]
1. Just the part of the style defined in the workspace. For example:

![Screenshot 2021-03-08 at 09 11 51](https://user-images.githubusercontent.com/1009874/110300123-6e099d80-7fee-11eb-8022-5119edd99344.png)

2. I just checked, and this functionality is not supported with any of the exports (PlantUML, Mermaid, etc) - it's only supported with the Structurizr renderer at the moment.

**Comment by MTomBosch** [comment]
Ok, thank you. Feel free to close this issue. It would be nice though to add your comments to my questions to the official docs so that it is clear how styles and themes work.
Ideally a small pseudo algorithm how styles are applied would be very nice.
e.g. If no style then default style is applied, if styles are used then no default style is used at all.
If themes are used with styles then...

Nevertheless I got the information I was seeking so I will close the issue. Thank you.

**Comment by simonbrowndotje** [comment]
Will do. Just to confirm though:

- which "official docs" are you referring to?
- what do you feel is missing?

At the moment, here are the docs pointed to by the DSL language reference:

- [Structurizr - Notation](https://structurizr.com/help/notation)
- [Structurizr - Themes](https://structurizr.com/help/themes)

**Comment by simonbrowndotje** [comment]
> I just checked, and this functionality is not supported with any of the exports (PlantUML, Mermaid, etc) - it's only supported with the Structurizr renderer at the moment.

I just added this support to the Java client library, and it's deployed at [https://structurizr.com/dsl](https://structurizr.com/dsl) if you want to take a look. It'll be in the next CLI release. In the examples below, the red border colour is taken from the theme, and the blue text colour is overridden in the workspace.

![Screenshot 2021-03-09 at 11 28 16](https://user-images.githubusercontent.com/1009874/110464122-a7afd680-80ca-11eb-97fc-11eab21fbe6e.png)

![Screenshot 2021-03-09 at 11 28 26](https://user-images.githubusercontent.com/1009874/110464127-a9799a00-80ca-11eb-8055-ec9c6599070f.png)
