### ISSUE TITLE
View Component include component with children

### ISSUE THREAD

**Issue by jgautheron** [structurizr/dsl#43]
Given the following:
```
apiApplication = container "API Application" "Desc" "Techno" {
    component1 = component "Test component 1" "Desc" "Techno" "Microservice"
    component2 = component "Test component 2" "Desc" "Techno" "Microservice"
    component1 -> component2
}
```

I'd like to create a component view showing only `component1` and its children, doing the following:

```
views {
    component apiApplication "Component1" {
        include component1 -> *
    }
}
```

But that won't work and will throw the following error (using Structurizr CLI v1.8.1):
```
com.structurizr.dsl.StructurizrDslParserException: The element "component1" does not exist in the view at line 211: include component1 -> *
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:561)
```

**Comment by simonbrowndotje** [comment]
Are you sure that error message is related? `gatewayPHPComponent` doesn't seem to exist in the snippet you posted.

**Comment by jgautheron** [comment]
You're right, updated 👍

**Comment by simonbrowndotje** [comment]
`include component1 -> *` is for including relationships between elements, not the elements themselves (screenshot attached from the DSL language reference).

<img width="699" alt="Screenshot 2021-03-19 at 17 24 31" src="https://user-images.githubusercontent.com/1009874/111819198-fc77fc00-88d7-11eb-8d3f-255380f5a725.png">

**Comment by jgautheron** [comment]
Would there be a way to do it, apart from enumerating every component in the `include`?

**Comment by simonbrowndotje** [comment]
Not at the moment. You could do an `include *` followed by one or more `exclude` statements. What is it you're trying to do, and how many components do you have?

**Comment by jgautheron** [comment]
I have about 30 components (microservice architecture), and not finished yet. About 15 are called by one gateway, and the other 15 through another.
Because of the amount of components, the generated image is cut on the sides, so I thought that I could split in two, one component view for each gateway.

Hence also my other question in structurizr/java, I'm considering rewriting the DSL in Java so I could forward an array to the component view.

**Comment by simonbrowndotje** [comment]
Right, in that case you'd need to explicitly specify the components that you want to include ... I'll have a think about how to add an expression into the DSL to support adding an element plus its direct connections.

> Because of the amount of components, the generated image is cut on the sides (another question: is it possible to increase the size of the image?), so I thought that I could split the view in two, one for each gateway.

Which renderer are you using?

> Hence also my other question in structurizr/java, I'm considering rewriting the DSL in Java so I could forward an array to the component view.

The Java client library will definitely provide more flexibility; there's an `addNearestNeighbours` method on `ComponentView`. What you gain with that convenience, you lose in other ways though (e.g. the Java code will be much more verbose).

Finally, and off-topic, and I may have misunderstood, but I wouldn't typically model microservices as components. That doesn't change any of the above, of course.

**Comment by jgautheron** [comment]
I am using the structurizr.com renderer (GraphViz).
Right my issue is related to the fact that I'm using components instead of containers for microservices. Splitting views by containers will be a much simpler undertaking.
Thanks!

**Comment by RobinCpl** [comment]
It would be great to be able to add an element and all of its children, direct and indirect

> Right, in that case you'd need to explicitly specify the components that you want to include ... I'll have a think about how to add an expression into the DSL to support adding an element plus its direct connections.
