### ISSUE TITLE
Support for multiple component layers

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/dsl#45]
We have systems with very few but very big containers (Eclipse IDE client application). Such a container consists of a few high level components which itself contain (sub-)components on its own (sometimes even one more component layer) until finally the code layer is reached.
It would be very helpful if the dsl and finally then also the cli and structurizr server would support multiple layers of components.

That means when defining views in the dsl it would be very helpful if only the directly contained elements are shown, that means the component view only shows the top level components of the given container. For lower component layers it would be nice if the "parent" component could be given as the context for the view.

**Comment by simonbrowndotje** [comment]
It's unlikely that multiple layers of components will ever be supported I'm afraid ... it's a very large across all of the tooling. From a more general perspective, I don't recommend that teams modify the layers in the C4 model approach either. Alternative visualisations (e.g. graphs) or slicing your diagrams may help you diagram large component models.
