### ISSUE TITLE
deploymentNode documentation is recursive

### ISSUE THREAD

**Issue by alastairs** [structurizr/dsl#46]
```markdown
### deploymentNode

The `deploymentNode` keyword is used to define a deployment node.
    
    deploymentNode <name> [description] [technology] [tags] [instances] {
         ...
    }
```

I'm struggling to work out how the `deploymentNode` keyword should be used and what the concept represents. Some examples of what this represents would be useful, such as those included in the `infrastructureNode` documentation. 

https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#deploymentnode

**Comment by simonbrowndotje** [comment]
Perhaps the description of the/example [deployment diagram at c4model.com](https://c4model.com/#DeploymentDiagram) will help?

**Comment by alastairs** [comment]
Yes, that did, many thanks Simon 👍🏻
