### ISSUE TITLE
!include with support for URLs

### ISSUE THREAD

**Issue by rcoates-deloitte** [structurizr/dsl#48]
Are there any plans/requests to add support for URLs to the `!include` capabilities?

I'm modeling a rather large workspace and many of the grouped software systems themselves reside in separate repos with their own models defined as a `.dsl`, rather than just allowing `!include` to reference local relative paths, it would be nice to point them to a raw github link or something (assuming auth could be a problem here if they are not public)

there are ways we can do some of this via build scripts if needed, but it makes validating and testing the model a little more painful

**Comment by simonbrowndotje** [comment]
Adding the ability to pull down a DSL fragment via a URL is straightforward, but leads to some complexity if that DSL fragment itself contains relative includes, `!docs`, `!adrs`, or tries to load icons from local resources. For that reason, I'd recommend an assemble phase that downloads all of the resources before running the DSL parser.

**Comment by rcoates-deloitte** [comment]
Ya we have similar requirements in the Open API Specification space, as we can have #refs to other components, response bodies, schemas etc and these can be at the bottom of the JSON/YAML file or external ones

Lots of the tooling has a `cli compile ./specfile.yaml` type of thing that will crawl the object model, follow all the external links and compile it all into a single file for further processing (such as `cli validate` or `cli build` etc

I'll go ahead and start working on some build scripts to try and mimic this, might be an idea for future cli inclusion if there is any more demand, I'm trying to grok enough Java to see if i can contribute and submit a PR but its not an ecosystem I'm very familiar with :)

Thanks for the response Simon

**Comment by coordt** [comment]
@rcoates-deloitte This is something I am looking for as well. I'd love to help if I can.

We need to be able for one micro service to say it depends on another microservice without redefining it. Then when multiple `.dsl` files are combined, all the links would be there.

**Comment by simonbrowndotje** [comment]
You can already split definitions across multiple files (see [the Big Bank example in the Structurizr CLI examples directory](https://github.com/structurizr/cli/tree/master/examples/big-bank-plc)) ... but only local file system includes are supported currently.

**Comment by coordt** [comment]
I like the split definitions, but the problem is when you have multiple teams responsible for their system. We really need a way to reference another system in relationships.

For example, three independent teams: web, mobile, and API. Each team maintains their own workspace document. How do the web and mobile teams refer to the API in a relationship? They can't import them because the API team has a workspace, and workspaces are nest-able.

If there was a way to make a reference like

```
web_ws = workspace {
    model {
        user = person "User" "A user of my software system."
        web = softwareSystem "Web App" "Our web app"
        api = softwareSystem "#ref: api_ws/model/api"
        user -> web "Uses"
        web -> api "Calls"
    }
}
```

Then you have the ability to assign an id or reference to a workspace, and then cross reference them.

**Comment by simonbrowndotje** [comment]
This is different, but somewhat related ... I'm also adding the ability to "extend" a workspace, allowing teams to start with a base workspace and add more elements, relationships, views, etc to it. [Here's an example](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/c8c7aac582f6956eb437a37330fa090f/raw/11b3b27a183698288a52d8fadba5b377b67354ad/gistfile1.txt).

**Comment by RobinCpl** [comment]
I like the structurizr at all and the possibility of splitting definitions across different files. But I have a question (sorry if silly).
**Where should be hosted files to let me to use include files. Should it be Structurizr server?** 
I'm using the free version of Structurizr so far and I'm wondering if paid version let me to upload files and the include will work well. Or maybe I should use "On-Premises" version?
Now I tried to use files saved on github, but as you can guess, it doesn't work. I have to include files via full url. Additionally, when I use private repository, it causes some other problems.
