### ISSUE TITLE
Support for URL on objects

### ISSUE THREAD

**Issue by Sport0142** [structurizr/dsl#5]
Hi @simonbrowndotje ,

There doesn't appear to be any support for setting the URL on any of the objects that accept it in the UI. It this something that can be added?

By the way, I'm really liking the DSL. I much prefer it over the UI. 

Cheers!

Kyle

**Comment by Sport0142** [comment]
Thanks for the quick turnaround @simonbrowndotje. Cheers!

**Comment by simonbrowndotje** [comment]
Thanks, you're welcome! This is included in v1.4.3 of the CLI, which I also just released.
