### ISSUE TITLE
Add the ability to get components cross container view

### ISSUE THREAD

**Issue by omriperi** [structurizr/dsl#52]
Hello!

Lately I'm working with Structurizr and having a lot of fun, but I'm looking for specific view I can't get by now.
I want to see a connection from one component in container to **other** component in container, and actually see in one view two different components from two different containers.

For example, let's look in this DSL:

`   model {
        customer = person "Personal Banking Customer" "A customer of the bank, with personal bank accounts." "Customer"

        enterprise "Big Bank plc" {
            supportStaff = person "Customer Service Staff" "Customer service staff within the bank." "Bank Staff"
            backoffice = person "Back Office Staff" "Administration and support staff within the bank." "Bank Staff"

            mainframe = softwaresystem "Mainframe Banking System" "Stores all of the core banking information about customers, accounts, transactions, etc." "Existing System"
            email = softwaresystem "E-mail System" "The internal Microsoft Exchange e-mail system." "Existing System"
            atm = softwaresystem "ATM" "Allows customers to withdraw cash." "Existing System"

            internetBankingSystem = softwaresystem "Internet Banking System" "Allows customers to view information about their bank accounts, and make payments." {
                singlePageApplication = container "Single-Page Application" "Provides all of the Internet banking functionality to customers via their web browser." "JavaScript and Angular" "Web Browser"
                mobileApp = container "Mobile App" "Provides a limited subset of the Internet banking functionality to customers via their mobile device." "Xamarin" "Mobile App" {
                    mobileAppComponent = component "Mobile App Component"
                }
                webApplication = container "Web Application" "Delivers the static content and the Internet banking single page application." "Java and Spring MVC"
                apiApplication = container "API Application" "Provides Internet banking functionality via a JSON/HTTPS API." "Java and Spring MVC" {
                    signinController = component "Sign In Controller" "Allows users to sign in to the Internet Banking System." "Spring MVC Rest Controller"
                    accountsSummaryController = component "Accounts Summary Controller" "Provides customers with a summary of their bank accounts." "Spring MVC Rest Controller"
                    resetPasswordController = component "Reset Password Controller" "Allows users to reset their passwords with a single use URL." "Spring MVC Rest Controller"
                    securityComponent = component "Security Component" "Provides functionality related to signing in, changing passwords, etc." "Spring Bean"
                    mainframeBankingSystemFacade = component "Mainframe Banking System Facade" "A facade onto the mainframe banking system." "Spring Bean"
                    emailComponent = component "E-mail Component" "Sends e-mails to users." "Spring Bean"
                }
                database = container "Database" "Stores user registration information, hashed authentication credentials, access logs, etc." "Oracle Database Schema" "Database"
            }
        }

        # relationships between people and software systems
        customer -> internetBankingSystem "Views account balances, and makes payments using"
        internetBankingSystem -> mainframe "Gets account information from, and makes payments using"
        internetBankingSystem -> email "Sends e-mail using"
        email -> customer "Sends e-mails to"
        customer -> supportStaff "Asks questions to" "Telephone"
        supportStaff -> mainframe "Uses"
        customer -> atm "Withdraws cash using"
        atm -> mainframe "Uses"
        backoffice -> mainframe "Uses"

        # relationships to/from containers
        customer -> webApplication "Visits bigbank.com/ib using" "HTTPS"
        customer -> singlePageApplication "Views account balances, and makes payments using"
        customer -> mobileApp "Views account balances, and makes payments using"
        webApplication -> singlePageApplication "Delivers to the customer's web browser"

        # relationships to/from components
        singlePageApplication -> signinController "Makes API calls to" "JSON/HTTPS"
        singlePageApplication -> accountsSummaryController "Makes API calls to" "JSON/HTTPS"
        singlePageApplication -> resetPasswordController "Makes API calls to" "JSON/HTTPS"
        mobileAppComponent -> signinController "Makes API calls to" "JSON/HTTPS"
        mobileApp -> accountsSummaryController "Makes API calls to" "JSON/HTTPS"
        mobileApp -> resetPasswordController "Makes API calls to" "JSON/HTTPS"
        signinController -> securityComponent "Uses"
        accountsSummaryController -> mainframeBankingSystemFacade "Uses"
        resetPasswordController -> securityComponent "Uses"
        resetPasswordController -> emailComponent "Uses"
        securityComponent -> database "Reads from and writes to" "JDBC"
        mainframeBankingSystemFacade -> mainframe "Makes API calls to" "XML/HTTPS"
        emailComponent -> email "Sends e-mail using"

     
    views {

        component apiApplication "Components" {
            include *
            animation {
                singlePageApplication mobileApp database email mainframe
                signinController securityComponent
                accountsSummaryController mainframeBankingSystemFacade
                resetPasswordController emailComponent
            }
            autoLayout
        }

        }
    }
}
`

Taken from this example with few modification: https://structurizr.com/dsl?example=big-bank-plc, and I'm taking a look on the component view:
`
        component apiApplication "Components" {
            include *
            animation {
                singlePageApplication mobileApp database email mainframe
                signinController securityComponent
                accountsSummaryController mainframeBankingSystemFacade
                resetPasswordController emailComponent
            }
            autoLayout
        }
`

The drawing we're having is:

![Screen Shot 2021-04-26 at 11 35 50](https://user-images.githubusercontent.com/26282864/116053624-91160c80-a683-11eb-9110-c3208560cb29.png)

Even though **component** inside the mobileApp container is communicating with one of the applications in the API Application container, the connection seems straight from the container itself. 
I know that's the intention, but what I wanted to have is the possibility to see also the component inside the "mobileApp" container with dotted lines around the mobileApp container.

I guess it will require a different view, because such kind of view not falling on any of component / container / SystemLandscape view. 
Such view (with inner components of several containers) can be quite loaded, so I guess using it with filtered view is the way to go (seeing only connection relevant to this drawing)

The benefit of this kind of view is seeing connection cross containers, and no only in the container level
In the project I'm working in, we're having few containers, each one of them including several processes (components). 
My wish is to demonstrate connection between components, and that's where this request coming from

Thanks! Omri

**Comment by simonbrowndotje** [comment]
You can show the connections between components, for example:

```
workspace {

    model {
        softwareSystem "Software System 1" {
            container1 = container "Container 1" {
                component1 = component "Component 1"
            }
        }

        softwareSystem "Software System 2" {
            container2 = container "Container 2" {
                component2 = component "Component 2"
            }
        }

        component1 -> component2 "Uses"
    }

    views {
        component container1 {
            include component1 component2
            autoLayout
        }
    }
    
}
```

Does that help?

**Comment by omriperi** [comment]
It is, thanks :)
But I would glad to see the context of the component found "outside" the view, in this case I'll get container1 with component1 in it, connected straight to copmonent2 without knowing from which container it originates.
Is it possible to see it as well?

Also, I red the documentation and didn't see there's option to use the include statement (in container / component view) with tags, only with specific elements - am I missing something? 

Thanks again, Omri

**Comment by simonbrowndotje** [comment]
If you try that fragment at https://structurizr.com/dsl you'll see that both container boundaries are drawn ... the Structurizr renderer supports this now, and the next version of the CLI will do the same for the PlantUML, Mermaid, and DOT exports.

<img width="425" alt="Screenshot 2021-04-26 at 10 00 03" src="https://user-images.githubusercontent.com/1009874/116056922-332ef800-a676-11eb-894c-7091a5dc359b.png">

![image](https://user-images.githubusercontent.com/1009874/116056961-3cb86000-a676-11eb-8e60-a681b888c8c3.png)

**Comment by simonbrowndotje** [comment]
> Also, I red the documentation and didn't see there's option to use the include statement (in container / component view) with tags, only with specific elements - am I missing something?

Yes, you can include elements by tag in container and component views -> https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#include

**Comment by omriperi** [comment]
Thanks a lot! I think that's it

I see that the PlantUML generation is working fine both in the Structurizr DSL webpage, but the C4Plantuml is different in the webpage and CLI (v1.9.0) (Based on the model you've provided in the comment)

DSL Webpage C4Plantuml generation:
`
@startuml
title Software System 1 - Container 1 - Components

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container_Boundary("2_boundary", "Container 1") {
  Component(3, "Component 1", "")
}

Container_Boundary("5_boundary", "Container 2") {
  Component(6, "Component 2", "")
}

Rel_D(3, 6, "Uses")
@enduml

`

CLI Generation:
`
@startuml(id=SoftwareSystem1-Container1-Component)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title Software System 1 - Container 1 - Components

Container_Boundary(2_boundary, Container 1) {
  Component(3, "Component 1", "", "")
  Component(6, "Component 2", "", "")
}
Rel_D(3, 6, "Uses", "")
@enduml
`

That yields to:
![Screen Shot 2021-04-26 at 12 19 44](https://user-images.githubusercontent.com/26282864/116059613-af7f0680-a689-11eb-92f3-6400c17c549c.png)

That's the issue you've talked about that will be solved in next CLI release or should I open an issue?
Other than that you've helped me a lot and I think I'll manage from here

THanks, Omri

**Comment by simonbrowndotje** [comment]
Thanks. No need to raise another issue ... what you see at structurizr.com/dsl is what will be in the next CLI release.

![image](https://user-images.githubusercontent.com/1009874/116060107-763e9a80-a679-11eb-9116-819c6d304862.png)

**Comment by georgd** [comment]
Was this functionality undone? I can see the components only if I don’t add a relationship between them, in plantuml and plantuml/c4plantuml exports.
