### ISSUE TITLE
Support parallel activities in dynamic view

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/dsl#53]
At the moment the dynamic view always resolves to a single sequence of activities.
But some flows are more than just a sequence of steps but also includes parallel steps.
It would be very nice if parallel activities (two or three times a 1. or 3.) could be defined too.

**Comment by simonbrowndotje** [comment]
I just put together a quick implementation in the DSL (this was already supported by the underlying Java library) ... try the following at [https://structurizr.com/dsl](https://structurizr.com/dsl) and let me know what you think:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            webapp = container "Web Application"
            bus = container "Message Bus"
            app1 = container "App 1"
            app2 = container "App 2"
        }

        user -> webapp "Updates details"
        webapp -> bus "Sends update event"
        bus -> app1 "Broadcasts update event"
        bus -> app2 "Broadcasts update event"
    }

    views {
        dynamic softwareSystem {
            user -> webapp
            webapp -> bus
            {
                bus -> app1
            }
            {
                bus -> app2
            }

            autoLayout
        }
    }

}
```

**Comment by MTomBosch** [comment]
Looks good, thank you a lot for the fast response.

Did a more complicated example to test it:

workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            webapp = container "Web Application"
            bus = container "Message Bus"
            app1 = container "App 1"
            app2 = container "App 2"
            app3 = container "App 3"
            app4 = container "App 4"
            app5 = container "App 5"
            app6 = container "App 6"
        }

        user -> webapp "Updates details"
        webapp -> bus "Sends update event"
        bus -> app1 "Broadcasts update event"
        bus -> app2 "Broadcasts update event"
    }

    views {
        dynamic softwareSystem {
            user -> webapp
            webapp -> bus
            {
                bus -> app1
                app1 -> app3
                app3 -> app4
                {
                    app4 -> app5
                }
                {
                    app4 -> app6
                }
            }
            {
                bus -> app2
                app2 -> app4
            }

            autoLayout
        }
    }

}

**Comment by MTomBosch** [comment]
Do you know when you will release a new version of it as part of the cli release?

**Comment by MTomBosch** [comment]
Any plans to release a new cli with this feature any soon?
