### ISSUE TITLE
Error Sorry, something went wrong.

### ISSUE THREAD

**Issue by luizfbicalho** [structurizr/dsl#54]
I'm having the error 

Sorry, something went wrong.

in the url 
https://structurizr.com/dsl

looks like is something wrong with the theme, but there is no explanation,

I open the theme correctly on the theme help 

https://structurizr.com/help/theme?url=https://raw.githubusercontent.com/luizfbicalho/structurizr/master/theme/alpargatas5.json

One problem found is the theme value is case sensitive

  "routing" :"Direct" is OK but   "routing" :"direct" gives the error

**Comment by simonbrowndotje** [comment]
The theme browser will now tell you what's wrong. And yes, some of the values are case sensitive ... `curved` vs `Curved`, `direct` vs `Direct`, etc.
