### ISSUE TITLE
Themes help page not showing Component Shape

### ISSUE THREAD

**Issue by luizfbicalho** [structurizr/dsl#55]
I created this theme
https://structurizr.com/help/theme?url=https://raw.githubusercontent.com/luizfbicalho/structurizr/master/theme/alpargatas.json

and when I display shows a broken image

![image](https://user-images.githubusercontent.com/16882855/118043158-61395b00-b34b-11eb-8d03-8766bba2b8b7.png)

**Comment by simonbrowndotje** [comment]
This is now fixed.
