### ISSUE TITLE
Add more advanced features for groups

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#57]
Nowadays structurizr allows creating groups of elements, but with some limitations: 
- It is not possible to create nested groups
- It is not possible to create relationships using groups (element from/to group, group from/to group). At least I was not able to make it working.
- An element cannot be part of more than one group. 
- When defining a group, we need to explicitelly list the elements in the group. We cannot create a group based on tags.
- They are automatially displayed. There is no option to decide if we want to group or not elements in a view. Or even select the specific grouping we want to see.

It would be great if we remove these limitations, allowing creating views like this:
- Layers: I could create some groups representing layers: Experience Layer, API Layer, .... and I could include elements in the group based on tags. Then, when rendering, I could see the elements together within the same layer.
- Domains: I could also create some groups representing domains: Consumer, Products, Orders, ... and I could include elements based on tags. Notice that a speficic element would be part of a Domain and Layer group, so in this view I would like to only group based on Domain and not on Layer.
- Ownership: In a very high level, I could group elements by owner areas within a big organization, having groups of groups. I could represent some elements in a group are connected to others in another group, without adding specific relationship between elements.

In case you think there is another recommended to get it, please let me know. Thanks!

**Comment by simonbrowndotje** [comment]
You're correct, the groups feature is just a way to group elements at the same level on a diagram. Removing these limitations essentially requires redeveloping the entire way that Structurizr works ... i.e. moving away from having a predefined set of abstractions (software systems, containers, and components) to an arbitrary set of hierarchical abstractions, with zooming and implied relationships at all levels. To set expectations, it's very unlikely this will happen I'm afraid.

**Comment by juanrferia** [comment]
Thanks Simon for quick response. I undertand your concerns, but before rejecting let me clarify something: I'm not suggeting different levels of abstractions, I do want to keep using the level of abstractions defined in C4 model. I'm suggesting these new features for groups just to have a way to group elements in the view based on some criteria. The views I described (Layers, Domains, Ownershop) are just the result we could get by using groups in the predefined set of abstractions. For example, let's say I have a System Context Diagram with big number of systems. I could create groups representing domains in a way I would see the containers grouped based on domains, so that would be easier to understand. Alternatively, or even additionally (as described in my request), I could decide on creating groups representing layers in a way I would see the systems grouped based on layers, so that would be easier to understand.  The same example could be valid for a Container Diagram.
In fact, I can patically achive that nowadays by creating groups, but with the limitations described.

**Comment by simonbrowndotje** [comment]
I'm not sure I understand what you're asking in that case. Let's look at this piece by piece. 

> I could create groups representing domains in a way I would see the systems grouped based on domains, so that would be easier to understand.

This seems possible with the current functionality - what's missing for you here?

```
workspace {

    model {
        1 = group "Domain 1" {
            a = softwareSystem "A"
            b = softwareSystem "B"
        }
        2 = group "Domain 2" {
            c = softwareSystem "C"
            d = softwareSystem "D"
        }
        
        a -> b
        b -> c
        c -> d
    }

    views {
        systemLandscape {
            include 1 2
            autoLayout lr
        }
    }
    
}
```

![image](https://user-images.githubusercontent.com/1009874/121520507-46faa780-c9f3-11eb-8d60-6d4a32780253.png)

**Comment by juanrferia** [comment]
Makes sense, let's go step by step. So, starting from your example, let's say that in addiction to landscape view grouping by domains, I want to create an separate landscape view grouping by layers. Then, for example, I would like to be able to create 2 new groups: Layer 1 and Layer 2 adding A+C and B+D, respectively. Then, the additional Landscape view would show:
![image](https://user-images.githubusercontent.com/11686949/121639625-1c5d2d00-ca8d-11eb-8e7d-068675179bd7.png)

So, for now, it is refering to some of my points: 
- An element cannot be part of more than one group.
- They are automatially displayed. There is no option to decide if we want to group or not elements in a view. Or even select the specific grouping we want to see.

**Comment by simonbrowndotje** [comment]
It's a similar reason to why I've resisted creating view-specific styling (i.e. styles that are only used on a single view) ... I want the views to show a consistent representation of the model. Creating an alternative version of the model, with different groupings can be done using the workspace extensions feature though, for example:

- [Base workspace with no groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/e53f2f9da44f6d4d5965bd9daec71a9e42b62f4c/gistfile1.txt)
- [Domain groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/daf82e15a59cd3a49af22a6f6cb63838ff858724/domains.dsl)
- [Layer groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/daf82e15a59cd3a49af22a6f6cb63838ff858724/layers.dsl)

**Comment by juanrferia** [comment]
Interesting! Honestly, I was not aware of that feature. Thanks for sharing. I'll explore it.
Let me then come to the next step

Let's assume I can achive my goals using the workspace extension feature. Then, on the new workspaces for Domains and Layers I would need to add the elements to the specific groups. In the example you shared, they are selected one by one. It would be great to add elements in a group based on tags. So, in the original workspace I can use the tags like "domain_1", "domain_2", "layer_1", "layer_2", and the views in the extended workspaces would automatically group elements accordantly. What do you think?

This is related to my point:
- When defining a group, we need to explicitelly list the elements in the group. We cannot create a group based on tags.

**Comment by simonbrowndotje** [comment]
Including elements by tag is very useful for views, where you only want to show a subset of the model. Having different groups is really about manipulating the model though ... and once you get to that stage, it's possibly time to break out of the DSL and into code. For example, with the Java client library and DSL parser as dependencies, you can do something like this:

```
    public static void main(String[] args) throws Exception {
        StructurizrDslParser parser = new StructurizrDslParser();
        parser.parse(new File("base-workspace.dsl"));
        parser.getWorkspace().getModel().getSoftwareSystems().stream().filter(ss -> ss.hasTag("Layer 1")).forEach(ss -> ss.setGroup("Layer 1"));

        // ...
    }
```

**Comment by juanrferia** [comment]
Sorry for the delay in my response. I see, thanks for sharing. 

I've been rethinking about this topic and wanted to share my thoughts: I have the feeling we can see groups from two different perspectives (probably two separate concepts).

On one hand, I fully agree with you on having groups as part of the model: for example, grouping systems in ecosystems, grouping containers in subsystems, grouping components in modules. I do have some usecases of groups in that sense, and some part of my initial request (for supporting relatioships and nested groups) are related to this concept of group. In this case, I also agree with you that doesn't make sense to implement a way to add elements to a group based on tags. 

On the other hand, there are some other usecases in which I see "grouping" (maybe we should use a different name) as a view feature, not part of the model, in which I'm basically interested on keeping elements together according to some criteria. In parctice, it would be like disabling autolayout and reorganizing the elements to manually group all of them according to that spefific criteria. From my view, this feature would help a lot and would provide lot of flexibility. In this case, as a "grouping" feature on views, creating "groups" based on tags makes more sense.

You know already shared some concerns related, but I would appreciate your feedback on this high level proposal

**Comment by mcbeelen** [comment]
> It's a similar reason to why I've resisted creating view-specific styling (i.e. styles that are only used on a single view) ... I want the views to show a consistent representation of the model. Creating an alternative version of the model, with different groupings, can be done using the workspace extensions feature though, for example:
> 
> * [Base workspace with no groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/e53f2f9da44f6d4d5965bd9daec71a9e42b62f4c/gistfile1.txt)
> * [Domain groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/daf82e15a59cd3a49af22a6f6cb63838ff858724/domains.dsl)
> * [Layer groups](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/d5b36ee7db809215fdd6be8b818fa252/raw/daf82e15a59cd3a49af22a6f6cb63838ff858724/layers.dsl)

I wanted to view the examples for the Domain Groups and Layer Group do not work anymore.
Both yield and error:

`The element is already registered with an identifier of "a" at line 5: softwareSystem "A"`
@simonbrowndotje Could you provide new versions?

**Comment by simonbrowndotje** [comment]
It doesn't look like this works any more ... feel free to raise a new issue.

**Comment by sroesch-haufe** [comment]
Since the discussion on extending features for groups is still open, I'd like to ask, if you consider to add the capability to set the background color of the box of the group or other stylings.
We are looking into using groups for different domains (as in the example in the [comments above](https://github.com/structurizr/dsl/issues/57#issuecomment-858556816)) - some simple coloring would be very handy and improve the readability of the diagram.
What do you think @simonbrowndotje ?

**Comment by maldini8626** [comment]
If you want to use nested groups you need to add in the model area addtional property
____________________________        
properties {
            "structurizr.groupSeparator" "/"
        }
-----------------------------
List of properties available here
https://structurizr.com/help/properties
