### ISSUE TITLE
Directory based includes

### ISSUE THREAD

**Issue by chrisjschultz** [structurizr/dsl#59]
Use Case: Using Structurizr to model an application landscape.

This goes against the recommendations for using Structurizr, but I have started to model a number (20ish) complex enterprise applications and how they integrate. We have tried this a number of times with UML and other techniques but have all failed, so I am trying it with C4 now :)

I have a models directory, and within that directories for:
- systems
- people
- relationships

I have a modified version of dsl which understands importing from directories.

Effectively I model systems in their own files, containing "within system" relationships in these files.

In the workspace I include the system in scope under "enterpise" and then import all systems next (this filters out the already loaded file in "enterprise"). Workspaces are generally containers for views.

Inter-thing relationships are seperate and included last so as to not require loading in a special order.

Is this something that is interesting? My current code breaks the file handling abstraction in the code a little, to dedeup file includes per workspace (I use Maven to generate all the models, and then also generate ascii doc extracts from the model to be included in other documents).

I can keep this as a private fork, or potenitally share for comment?

Thanks
Chris

=snip=

`
workspace "My System" "System which supports integration" {
    model {

        enterprise "My System" {
            !include high-level-system/my-system.dsl
        }

        # Include related Systems here
        !include high-level-system

        # Include related People here
        !include transpower-people
        !include customer-people
        !include relationships

    }

    views {

        systemLandscape CriticalESBSystemLandscape "All Systems in the ESB System Context" {
            autoLayout
`

**Comment by simonbrowndotje** [comment]
If it's working for you, then perhaps best to keep it as a private fork ... I have a feeling that the de-dupe logic might trip people up. But thanks for asking!

**Comment by chrisjschultz** [comment]
I figured, but thought it was worth checking. The logic is to just stop importing any file twice (if it is already imported in enterprise, don't import it again). This would actually also work if you included the same file twice (which would error out now).

**Comment by im-bpriestman** [comment]
This is something that I would have found very useful.

I'm also trying to model a distributed architecture made of many services. 

One way of doing this is in one big dsl-based model, using includes to include files which individual teams can 'own'. I've found that this works, if you make sure to define all your people and software systems, before then defining containers and relationships within those systems. It requires a _lot_ or repetitive include statements, though. Adding or changing a model of system involves adding some files and then adding references to each of them in the main dsl.

Maintenance of this would be a lot easier, if I could say something like:

```
!include systems/
!include containers/
```

I'm not so bothered about the de-duping mechanim.

@simonbrowndotje , could you clarify whether, in addition to rejecting the idea of a de-duping mechanism, you were also resistant to the notion of including directories of files?

**Comment by chrisjschultz** [comment]
The dedup is required to avoid parsing the same file twice, so kinda hand in hand.

This has been really useful, we have documentation for over 30 systems so far in our repo.

I wrapped the parsing and generation in our own Java layer with the modified DSL library. The reason behind this is that I also generate asciidoc snippets from the model, so eventually we can move all of our product documentation to asciidoc and include model extracts on each build so our documentation remains fresh along side our models.

The DSL mods are more or less trivial, if not a bit ugly. They are in a private repo, but I could publish this on github if it is useful?

**Comment by simonbrowndotje** [comment]
> could you clarify whether, in addition to rejecting the idea of a de-duping mechanism, you were also resistant to the notion of including directories of files?

It's the de-dup logic that I'm not keen on, but I've added some basic support for including a directory.

**Comment by chrisjschultz** [comment]
OK - the dedup logic is there to allow me to add a file reference specially in the enterprise tag. Its probably better phrased as "ignore already parsed files that I find in a directory" logic.

**Comment by im-bpriestman** [comment]
@simonbrowndotje, wow, that's responsive! Those changes look like just what I was after. I've been puzzling over this for weeks, so any time is good but can I ask what your release cycle is like? ie: when is this change likely to appear in the CLI, Lite or the webapp?

@chrisjschultz I can see why you'd want the dedupe logic. In my case, I'm happy to arrange my directory layout to work with blanket includes.

**Comment by simonbrowndotje** [comment]
This is now available in Lite, and will be available in the next CLI release (perhaps this week or next).

re: de-dup ... I've seen people doing things like the following, which is why I don't really want to add it:

```
workspace {

    model {
        softwareSystem = softwareSystem "Software System" {
            webapp1 = container "Web App 1" {
                !include common-components.dsl
            }

            webapp2 = container "Web App 2" {
                !include common-components.dsl
            }
        }
    }

}
```

**Comment by chrisjschultz** [comment]
OK, so people are using the "hierarchical" definition to achieve that. That is a little more tricky I guess. This would be the only scenario where it would be an issue I think?

**Comment by iambic69** [comment]
Hi @simonbrowndotje.  I'm working for the same organisation as @chrisjschultz.  Recently I've come up with an alternative approach to address our Enterprise-wide use case, which doesn't involve forking the DSL parser, or using !include to build the Enterprise-wide workspace.  Instead, separate workspace DSL files are parsed individually, and then merged.  The benefit is that our individual system workspaces are compatible with standard Structurizr products.  They're also more conventional, with everything in one file, not spread out over DSL fragments.

I pitched the idea to Chris yesterday, and am keen to get your feedback too.  You can see it here: https://github.com/iambic69/structurizr-tools

There are a couple of specific points I'd like your thoughts on:

- Whether you'd consider adding this functionality to WorkspaceUtils at some point?
- Whether this could be a good use of the, now deprecated, 'enterprise' syntax?  I.e. using element Location = External, rather than an 'External' tag.  This is something Chris suggested when I showed him yesterday.

I can raise this as a separate issue, of course, if you're interested to discuss it further, but I thought I'd mention it here first, in the context of the previous discussion.

Andrew
