### ISSUE TITLE
Visual Studio Code support

### ISSUE THREAD

**Issue by socadk** [structurizr/dsl#6]
Hi there, I got the DSL example to work in less than 5 mins, thanks for having documented it so well! How about "IDE" support for it, for instance Visual Studio Code? Apologies if I missed the instructions about it...

C4 does qualify as a [mighty method](https://ecsa2020.disim.univaq.it/details/ecsa-2020-keynotes/3/Mighty-Methods-Four-Essential-Tools-for-Every-Software-Architect-s-Silver-Toolbox) in Michael Keeling terms :-)

**Comment by simonbrowndotje** [comment]
Thanks, glad it's working out for you! This is the only VS Code add-on that I'm aware of (and I have no plans to build anything myself) -> https://marketplace.visualstudio.com/items?itemName=ciarant.vscode-structurizr
