### ISSUE TITLE
Jetbrains IDEs integration

### ISSUE THREAD

**Issue by antoinemichaud** [structurizr/dsl#63]
Hello,

It would be a great productivity improvement, and may be a better adoption incentive of structurizr for the ones using Jetbrains IDEs such as IntelliJ to have an integration as for what has been done for VSCode. 

What do you think about it ?

Thank you,

**Comment by simonbrowndotje** [comment]
I have no plans to do this myself, but I'm also a Jetbrains user, and would love to see some integrated tooling too.

**Comment by rvdwijngaard** [comment]
+1

**Comment by simonbrowndotje** [comment]
Closing the issue ... if anybody builds this integration, please get in touch and I'll add a link from this repo.
