### ISSUE TITLE
Setting default tag for elements in scope of views

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#65]
Hello,

I would like to automatically apply a blue color for the elements in scope of a view, while the elements our of scope keep being grey. Currently, I can achieve that by assigning tags to elements and defining a stiles for those tags, but then the elements are displayed always with the same stile for all views, regardless they are in or out of scope.

Let me explain with an example.

Given this workspace:

```
workspace {

    model {
    
        enterprise "My Enterprise" {
            
            softwareSystem1 = softwareSystem "Software System 1" {
                api1 = container "API"
            }
    
            softwareSystem2 = softwareSystem "Software System 2" {
                api2 = container "API"
            }
        
        }
        
        thirdPartySystem = softwareSystem "Third Party System"
        
        api1 -> api2
        api2 -> thirdPartySystem
        
    }
    
    views {
        
        systemlandscape "SystemLandscape" {
            include *
            autoLayout
        }
        
        systemcontext softwareSystem1 "softwareSystem1_SystemContext" {
            include *
            autoLayout
        }
        
        systemcontext softwareSystem2 "softwareSystem2_SystemContext" {
            include *
            autoLayout
        }
        
        container softwareSystem1 "softwareSystem1_Containers" {
            include *
            autoLayout
        }
        
        container softwareSystem2 "softwareSystem2_Containers" {
            include *
            autoLayout
        }
    }
}
```

I would like to get these views:

SystemLandscape:
![image](https://user-images.githubusercontent.com/11686949/128216983-6919e03c-398c-436c-a33e-8fe5798b1bc7.png)

softwareSystem1_SystemContext:
![image](https://user-images.githubusercontent.com/11686949/128217309-78c4d40b-6e9b-4436-8325-8e5c9254b51f.png)

softwareSystem2_SystemContext:
![image](https://user-images.githubusercontent.com/11686949/128217401-fdc6f275-b073-448f-9080-98072b5838c1.png)

softwareSystem1_Containers:
![image](https://user-images.githubusercontent.com/11686949/128217647-33d6c7ac-b502-4ae2-80b4-21d14c814b7c.png)

softwareSystem2_Containers:
![image](https://user-images.githubusercontent.com/11686949/128217771-36c6413b-e05e-47d3-a6df-070dd3f56dbb.png)

Is it maybe possible to automatically apply some default tag to the elements in scope? That would be a way to make it happen. If there is any existing way to achieve my goals, please let me know.

Thanks.

**Comment by simonbrowndotje** [comment]
For consistency reasons, view specific styles are not supported I'm afraid. You can achieve this via the workspace extension mechanism though (see https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#workspace), as follows:

1. Create a base workspace that contains all of your model elements, and any common styles.
2. Extend this base workspace, creating a view and view specific styles.

**Comment by juanrferia** [comment]
Thanks for the clarification
