### ISSUE TITLE
System Context diagram hides some contaner level relationships

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#66]
Hello,

A System Context diagram usually shows relationships defined at container level, represeting the relationship in the context of the system. So, for example, if I define a system A which contains a container A1 with a relationship with a system B, then the System Context diagram shows that a relationship between system A and system B. 

However, when multiple containers within a System are connected to the same system, then the System Context diagram only shows one of the relationships. If I define tags for those relationships and try to show the one I'm interested in, the diagram is not working as expected.

Given the following example:

```
workspace {

    model {
    
        enterprise "My Enterprise" {
            
            softwareSystem1 = softwareSystem "Software System 1"{
                api1 = container "API 1"
                api2 = container "API 2" 
            }

        
        }
        
        thirdPartySystem = softwareSystem "Third Party System"
        
        api1 -> thirdPartySystem "via API 1" "" "tag1"
        api2 -> thirdPartySystem "via API 2" "" "tag2"
        
    }
    
    views {
        
        systemlandscape "SystemLandscape" {
            include *
            autoLayout
        }
        
        systemcontext softwareSystem1 "softwareSystem1_SystemContext" {
            include *
            autoLayout
        }
        
        systemcontext softwareSystem1 "softwareSystem1_SystemContext_tag1" {
            include *
            exclude "relationship.tag==tag1"
            autoLayout
        }


    }
} 
```

I would expect the diagram "softwareSystem1_SystemContext_tag1" to show a relationship "via API 2". 
Additionally, it would be great if the diagram "softwareSystem1_SystemContext" shows both somehow. Something like "via API 1; via API 2".

Thanks,

**Comment by simonbrowndotje** [comment]
I've added a cookbook entry about how implied relationships work - [Multiple implied relationships](https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships#multiple-implied-relationships) explains what's happening here.

**Comment by juanrferia** [comment]
Thanks for sharing. That means the behaviour is expected. I could change the behaviour by using the java client and implementing my own strategy for implied relationship. Correct?

**Comment by simonbrowndotje** [comment]
Yes, using the Java client (rather than the DSL) will give you more control. There is a [CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy](https://github.com/structurizr/java/blob/master/docs/implied-relationships.md#createimpliedrelationshipsunlesssamerelationshipexistsstrategy) already built ... this could be integrated into the DSL (it sounds great in theory, but doesn't work well in practice ... it tends to result in an explosion of relationships, making diagrams very cluttered).

**Comment by juanrferia** [comment]
Hello @simonbrowndotje. I'm interested on using the CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy, hiding unwanted relationships via tags. So I would be able to show only the relationship I'm insterested in, depending on the view, avoiding that explosion of relationships you mentioned.

Having in mind my model is already defined via DSL, I'm trying something like this:

```
StructurizrDslParser parser = new StructurizrDslParser();
parser.parse(new File(workspacePath));
Workspace workspace = parser.getWorkspace();
workspace.getModel().setImpliedRelationshipsStrategy(new CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy());
```
Is this approach supposed to be working? I was not able to make it working yet.

Thank you

**Comment by simonbrowndotje** [comment]
The implied relationship strategy needs to be configured before creating elements and relationships, so that won't work unfortunately. I've just added a way to configure a custom strategy, which will be in the next release.

**Comment by simonbrowndotje** [comment]
Just to revisit this, the new support for scripting languages provides a way to change the strategy. For example, you can use this near the top of your DSL file:

```
!script groovy {
  workspace.model.impliedRelationshipsStrategy = new com.structurizr.model.CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy()
}
```

(if you need to create your own strategy, you'll need to get that on the CLI/Lite classpath, and the new plugin support might work best in that situation)

A new version of the CLI hasn't been released yet, but scripting support is now available via Lite.
