### ISSUE TITLE
How does relationship==* work?

### ISSUE THREAD

**Issue by venthur** [structurizr/dsl#68]
according to the [docs](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#expressions)

Things like this should be allowed in views

> relationship==*->*: all relationships

However when I try something like

```
systemLandscape foo "foo" {
    include element.tag==foo
    include relationship==*
    autoLayout
}

```
I get the error:
> The element/relationship "*" does not exist 

can you give a concrete example, or a better explanation in the docs how this is supposed to be used?

What I'm trying to achieve is to get all the elements with the tag "foo" but also all other elements that have an in- or out-bound relationship with them.

**Comment by simonbrowndotje** [comment]
`relationship==*` is a shortcut for `relationship==*->*`, although it appears that only works for `exclude` and not `include` ... I will add that.

> What I'm trying to achieve is to get all the elements with the tag "foo" but also all other elements that have an in- or out-bound relationship with them.

I don't think that's possible at the moment.
