### ISSUE TITLE
Identifiers hierarchical and deploymentEnvironment

### ISSUE THREAD

**Issue by pjjv** [structurizr/dsl#69]
Hello,

after I started to use identifier hierarchical this does not work:

     workspace {
     !identifiers hierarchical
 
    model {
        user = person "User"
        softwareSys = softwareSystem "Software System" 

        deploymentEnvironment Prod {

            DN1 = deploymentNode DN1 {
                softwareSystemInstance softwareSys 
            }
            
            DN2 = deploymentNode DN2 {
                softwareSystemInstance softwareSys 
            }
            
            DN1 -> DN2 "Hot stand by"
        }
    }

    views {
        theme default
        deployment * Prod {
            include *
        }
    }
    }

but this works:

    workspace {
    !identifiers flat
 
    model {
        user = person "User"
        softwareSys = softwareSystem "Software System" 

        deploymentEnvironment Prod {

            DN1 = deploymentNode DN1 {
                softwareSystemInstance softwareSys 
            }
            
            DN2 = deploymentNode DN2 {
                softwareSystemInstance softwareSys 
            }
            
            DN1 -> DN2 "Hot stand by"
        }
    }

    views {
        theme default
        deployment * Prod {
            include *
        }
    }
    }

How can it be done properly in hierarchical mode?

**Comment by simonbrowndotje** [comment]
That should work, so I'll take a look, but you can do this as a workaround:

```
 workspace {
    !identifiers hierarchical

    model {
        user = person "User"
        softwareSys = softwareSystem "Software System" 
    
        prod = deploymentEnvironment Prod {
    
            DN1 = deploymentNode DN1 {
                softwareSystemInstance softwareSys 
            }
            
            DN2 = deploymentNode DN2 {
                softwareSystemInstance softwareSys 
            }
            
            prod.DN1 -> prod.DN2 "Hot stand by"
        }
    }
    
    views {
        theme default
        deployment * Prod {
            include *
        }
    }
}
```

**Comment by pjjv** [comment]
Thank you, workaround works for me.

Tested also with deeper deploymentNode hierarchies, relative does not work within deploymentEnvironments, absolute path works well.
