### ISSUE TITLE
Hide a relationship in a view

### ISSUE THREAD

**Issue by tommysanterre** [structurizr/dsl#7]
I have a system with slightly different component based on the deployed configuration.
Depending on the configuration certain component may lose responsibilities that I want to illustrate with relationship.
Is it possible to exclude a relationship from a view?

    workspace  {

        model {
            mySystem = softwareSystem "My system" {
                componentA = container "A"
                componentB = container "B"
            }
            
            otherSystem = softwareSystem "The other system"
            
            componentA -> componentB "Do it for me"
            componentB -> otherSystem "Do it"
            componentA -> otherSystem "No B i'll do it myself"
        }

        views {
            container mySystem "ConfigurationA" {
                include *
                # Error The element/relationship "->" does not exist at line 20: exclude componentA -> otherSystem
                # exclude componentA -> otherSystem
                autoLayout
            }
            
            container mySystem "ConfigurationB" {
                include *
                exclude componentB
                autoLayout
            }
        }
    }

**Comment by simonbrowndotje** [comment]
Yes, you can assign an identifier to the relationship, and exclude that. For example:

```
workspace  {

    model {
        mySystem = softwareSystem "My system" {
            componentA = container "A"
            componentB = container "B"
        }
        
        otherSystem = softwareSystem "The other system"
        
        componentA -> componentB "Do it for me"
        componentB -> otherSystem "Do it"
        rel = componentA -> otherSystem "No B i'll do it myself"
    }

    views {
        container mySystem "ConfigurationA" {
            include *
            exclude rel
            autoLayout
        }
        
        container mySystem "ConfigurationB" {
            include *
            exclude componentB
            autoLayout
        }
    }
}
```

**Comment by tommysanterre** [comment]
Oh I see. Awesome. Thanks!

**Comment by simonbrowndotje** [comment]
You're welcome!

**Comment by florianmutter** [comment]
Does it also work the otherway round? Exclude all relationships except the ones that are in include?

**Comment by simonbrowndotje** [comment]
It doesn't. Relationships are automatically added based upon the elements in the view.

**Comment by radekwlsk** [comment]
@simonbrowndotje Just letting you know that it does not work for Deployment Diagram, where it could be the most useful when load balancers, proxies etc. are used to pass the flow between containers.

Should I open an issue or is there another option to do it for deployment?
