### ISSUE TITLE
How do refs work?

### ISSUE THREAD

**Issue by venthur** [structurizr/dsl#71]
In the example, there is [one](https://github.com/structurizr/dsl/blob/13f9ffd4caa639dd391b0345036333427987020e/examples/ref.dsl) that mentions `ref`, but it is not documented anywhere. Can you explain how it works? I see a pull request that tries to fix that but even from the diff, I don't really understand it. Does it only work in conjuction with `extends` or can I also use it to further refine an existing element that is defined in another file and included using `!include`?

**Comment by simonbrowndotje** [comment]
It's a work in progress/experimental/hidden feature. It can be used with `extends`, `!include`, or just on its own to find an element given a "canonical name" (this is a unique name that an element can be identified by in the model). If you have the Structurizr CLI, you can use the `list` command to list all elements by canonical name in a given workspace.

```
./structurizr.sh list -workspace getting-started.dsl

 - Person://User
 - SoftwareSystem://Software System
```


And here's a standalone example of `ref`:

```
workspace {

    model {
        softwareSystem "Software System"
        
        softwareSystem = ref "SoftwareSystem://Software System" {
            tags "Hexagon"
        }
    }

    views {
        systemLandscape {
            include *
            autolayout
        }

        styles {
            element "Hexagon" {
                shape hexagon
            }
        }
    }
    
}
```

> can I also use it to further refine an existing element that is defined in another file and included using !include

Yes, the target use case is adding content an existing element in a workspace that you're extending or fragments that you're including.

**Comment by venthur** [comment]
Wow! Thanks for the swift reply! It is indeed well hidden, and incredibly useful!

There seems to be a bug, though (I know it is experimental, but still...) part before `://` in the "canonical name" seems to be case sensitive, while the DSL is actually not.  `ref "container://foo"` does not work but `ref "Container://foo"` does. This is a bit confusing as the DSL allows for `= container {`, `= Container {` and even `= CoNtAiNeR {` in the definition.

**Comment by simonbrowndotje** [comment]
Yes, canonical names are case-sensitive too. For example, this will also fail:

```
workspace {

    model {
        softwareSystem "Software System"
        
        softwareSystem = ref "SoftwareSystem://software system" {
            tags "Hexagon"
        }
    }

    views {
        systemLandscape {
            include *
            autolayout
        }

        styles {
            element "Hexagon" {
                shape hexagon
            }
        }
    }
    
}
```

**Comment by venthur** [comment]
For the name part, I assumed so. I just wonder if the "scheme" part (i.e. `SoftwareSystem`) is intentional, since the corresponding keywords are explicitly not case sensitive or if it is a bug.
