### ISSUE TITLE
How about support use a local plantuml to render the graph.

### ISSUE THREAD

**Issue by Gowa2017** [structurizr/dsl#72]
Now, we use the  https://kroki.io/plantuml to render, but it some time slowly.

So, need a support of local render.

**Comment by simonbrowndotje** [comment]
Local rendering is already possible ... you can use the [Structurizr CLI export command](https://github.com/structurizr/cli/blob/master/docs/export.md) to export the views in a DSL workspace to PlantUML definitions, which you can then render with your own local installation of PlantUML.
