### ISSUE TITLE
Is it possible to make the parser indifferent to the order in which elements, relations, etc appear in the model?

### ISSUE THREAD

**Issue by venthur** [structurizr/dsl#75]
Currently the parser seems to be very strict about the order in which elements and relations are defined in the model. You cannot reference- or create a relation to an element that did not appear in the file yet, so to speak.

Or more explicitly, this works:
```
    model {
        bar = softwareSystem "Software System Bar"
        bar2 = ref "SoftwareSystem://Software System Bar"
    }
```
this does not:
```
    model {
        bar2 = ref "SoftwareSystem://Software System Bar"
        bar = softwareSystem "Software System Bar"
    }
```
While this is easy to handle in the above example, this becomes problematic if you have a modular setup, like so:

```
workspace {

    !identifiers hierarchical

    model {

        !include team_a/model.dsl
        !include team_b/model.dsl
        !include team_c/model.dsl

        # relations go here, below the definitions
        !include team_a/relations.dsl
        !include team_b/relations.dsl
        !include team_c/relations.dsl
    }

    views {

        systemLandscape "full" {
            include *
            autoLayout
        }

        theme default
    }
}
```
and the individual team's `model.dsl` use `ref` to reference other team's elements to augment them. The of order of `!include`s becomes suddenly very important as you cannot `ref` (or create a relation to-) something that the parser hasn't "seen" yet. In the above example, team B can `ref` something from team A but team A cannot `ref` something from team B at the same time, without creating circular imports, which are also not allowed as they lead to (re-)definitions of already existing elements.

Is it possible to make the parser indifferent to the order in which elements, relations, etc. are defined as long as they are all present in the `model`?

**Comment by simonbrowndotje** [comment]
> Is it possible to make the parser indifferent to the order in which elements, relations, etc. are defined as long as they are all present in the model?

Not without rewriting the parser ... sorry!
