### ISSUE TITLE
How does one apply a different style depending on the view?

### ISSUE THREAD

**Issue by chmduquesne** [structurizr/dsl#77]
I notice that the [`view`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#views) blocks can contain [`styles`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#views) block, however it seems that the views themselves ([`systemLandscape`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#systemLandscape-view), [`systemContext`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#systemcontext-view), [`container`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#component-view)...) cannot be styled independently. This is counter intuitive to me: I would have expected to be able to style things differently depending on the view.

When showing a system (for example in a [`systemContext`](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#systemcontext-view) view), it would be interesting to highlight this system and show external systems in a different color. For example, if we look at this example from the [c4model website](https://c4model.com), it is clear that the system being shown is the "Internet banking system".

![](https://c4model.com/img/bigbankplc-SystemContext.png)

However if I would draw the system context of e.g. the "Mainframe banking system" from the same image, I would clearly swap styles for "Internet banking system" and "Mainframe banking system", to show the "Mainframe banking system" in blue and the other systems in grey.

Is there a way to achieve that in the same worskpace? or do all views of the same workspace automatically have the same style? Do I need a different workspace for each view that I want to style differently?

**Comment by simonbrowndotje** [comment]
> do all views of the same workspace automatically have the same style?

Yes, you'll need to split diagrams across workspaces if you'd like to style them differently.

**Comment by simonbrowndotje** [comment]
The splitting of workspaces here is referring to rendering the same element differently. For example:

- https://structurizr.com/share/28201/diagrams#SystemLandscape ... the Internet Banking System is gray
- https://structurizr.com/share/36141/diagrams#SystemContext ... the Internet Banking System is blue

(those two workspaces are created using two separate DSL files, with the workspace extension mechanism, and each has different styling -> https://github.com/structurizr/cli/tree/master/examples/big-bank-plc)
