### ISSUE TITLE
Add support for defining notes

### ISSUE THREAD

**Issue by buger** [structurizr/dsl#79]
Hi! 

I really love your project!

However, the examples you have, have pretty simple short relationships between components. 
In some cases, especially using dynamic diagrams, I really would like to put more long form explanations, like `Talks to IDP, cache JWT token in memory/redis for 24h, inject to Header`. However, such long text does not fit well to diagram, when attached to relationship. For sure, it can be simplified by adding separate "IDP" system, "cache" component and "header injection" component, but then the diagram becomes a bit too bloated. I want to give more details without going too deep on component level.

Do you have plans to add support for adding notes, like PlantUML, or maybe there are some tricks which I can use right now?

Thanks!

**Comment by simonbrowndotje** [comment]
Thanks! You can do something like this (enable tooltips on the diagram viewer to see the detail when hovering the mouse pointer over the relationship).

```
workspace {

    model {
        a = softwareSystem "A"
        b = softwareSystem "B"
        
        a -> b "Talks to IDP" {
            properties {
                "Notes" "Cache JWT token in memory/redis for 24h, inject to Header"
            }
        }
    }
    
    views {
        systemLandscape "key" {
            include *
            autolayout lr
        }
    }
    
}
```

![image](https://user-images.githubusercontent.com/1009874/132460467-5b542266-5666-431c-87a5-7921336d00fc.png)

I keep meaning to add an extended description field, which will show up better in the tooltip, but that's still on the todo list.

**Comment by buger** [comment]
Thanks! 

Well dynamic diagram is hard to embed in some cases, like Github Readme, so I would rather find some graphical solution.

**Comment by simonbrowndotje** [comment]
Since you plan to [add notes to the PlantUML output](https://github.com/structurizr/java-extensions/issues/59), I'm going to close this issue.

**Comment by buger** [comment]
To be frank I would love having it in structurizr since one of the key features for me is ability to use manual placing instead of auto layout. PlantUML is more a plan B with a lot of downsides.

**Comment by simonbrowndotje** [comment]
There are no plans to add a graphical solution I'm afraid. I'd generally recommend using the interactive versions of the diagrams; either via the paid cloud service/on-premises installation, or the free Structurizr Lite Docker container.
