### ISSUE TITLE
Can you please quickly describe how to use the `!script` environment?

### ISSUE THREAD

**Issue by chmduquesne** [structurizr/dsl#82]
Hi,

I would like to use the script environment to prevent multiple relationships between the same systems. I was thinking about putting a

```
        !script groovy {
            ....
            throw new Exception("Multiple relationships between the same systems")
        }
```

However I am struggling, because I do not know what is available to the script environment for me to iterate. In python-like pseudo code, what I want to do is:

```
      for e in workspace.Model.elements:
          destinations = set()
          for r in e.relationships:
              # we already know this destination
              if r.destination in destinations:
                  raise Exception("Multiple relationships between r.source and r.destination")
              else:
                  destinations.add(r.destination)
           # now we scan the destinations for a backwards relationship
           for d in destinations:
               for r in d.relationships:
                   if r.destination == e:
                       raise Exception("Multiple relationships between r.source and r.destination")
```

I get that in groovy, this algorithm might look a bit different. What I am trying to understand is whether `workspace.Model` has e.g. an attribute `elements` I can iterate upon, and whether elements have attributes such as `relationships` (or a method `getRelationships()`), and if relationships have an attribute such as `source`, or if it is more a method like `getSource()`.

In other terms, I am trying to understand the interface of the workspace.

I am totally new to groovy, so forgive me if I am missing the obvious.

Thank you!
Christophe-Marie

**Comment by simonbrowndotje** [comment]
The scripting support provides you full access to the underlying Structurizr for Java library, the source code for which can be found at https://github.com/structurizr/java/tree/master/structurizr-core/src/com/structurizr

Although it's a Java library, it is interoperable with Groovy.

**Comment by chmduquesne** [comment]
I eventually figured this out.

This script enforces that there is no more than 1 relationship between any 2 elements. You want to add it after defining the model. You have to make sure that `!impliedRelationships` is set to `false`, otherwise it will flag relationships that you did not explicitly create (maybe those could have a tag "impliedrelationship" so that it can ignore them). I wish it was available as a default option!

```groovy
!script groovy {
    Set elements = workspace.model.getElements()
    elements.each{ e ->
        Set destinations = []
        e.getRelationships().each{ r->
            if (!r.hasTag("fixme")) {
                d = r.getDestination()
                if (d in destinations) {
                    throw new Exception("Relations ${e} -> ${d} exists multiple times")
                } else {
                    destinations.add(d)
                } } }
        destinations.each{ d->
            d.getRelationships().each { r->
                if (!r.hasTag("fixme")) {
                    if (r.getDestination() == e) {
                        throw new Exception("Relation ${e} <-> ${d} exists in both directions")
                    } } } } }
}

```
