### ISSUE TITLE
Multiple relationships display on the System Context view

### ISSUE THREAD

**Issue by chrisjschultz** [structurizr/dsl#84]
I don't know if this is by design or not, however.

When rendering a system context view, all relationships between systems are rendered "system -> system" and "container -> container" relationships are all renderered.

I intended to create system -> system relationships to act as an agreagtion in the System context view. In a container view, container to System links make sense. I THOUGHT Strcturizr was just picking one container -> system relationship on the context view, but it is actually rendering all of them

I did some more testing and it appears that the FIRST container -> container is rendered along with the system -> system if THE system -> system is NOT defined as the first relationship.

Here is an example:

```
 workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            webapp = container "Web Application" {
                user -> this "Uses"
            }
            webapp5 = container "Web Application 5" {
                user -> this "Uses"
            }
            container "Database" {
                webapp -> this "Reads from and writes to"
            }
        }
        softwareSystem2 = softwareSystem "Software System 2" {
            webapp2 = container "Web Application 2" {
                user -> this "Uses"
            }
            webapp3 = container "Web Application 3" {
                user -> this "Uses"
            }
            webapp4 = container "Web Application 4" {
                user -> this "Uses"
            }            
        }
        
        
        webapp -> webapp4 "con4->con4"
        webapp -> webapp2 "con2->con2"
        webapp -> webapp3 "con3->con3"
        webapp5 -> webapp2 "con5->con2"
        softwareSystem -> softwareSystem2 "sys->sys"
        
        
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout lr
        }

        container softwareSystem {
            include *
            autolayout lr
        }

        theme default
    }

 }
```

![image](https://user-images.githubusercontent.com/6622223/135939514-5f4ad7ea-e0cb-4be4-9ba4-3ad68b439cc4.png)

![image](https://user-images.githubusercontent.com/6622223/135939538-2e948922-3fe0-48e1-ad2f-c00277871482.png)

**Comment by simonbrowndotje** [comment]
> I don't know if this is by design or not

It's the [implied relationships](https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships) feature in action.

**Comment by chrisjschultz** [comment]
Thanks, yes I have seen that behavior, I had expected that when I added the system -> system link it would take precedence, but ordering of defintion matters.

```
    private Workspace parseWorkspace(String fileName) throws Exception {
        logger.debug("Parsing Workspace: {}", fileName);
        StructurizrDslParser p = new StructurizrDslParser();
        p.parse(new File(fileName));
        p.getWorkspace().getModel().setImpliedRelationshipsStrategy(new CreateImpliedRelationshipsUnlessAnyRelationshipExistsStrategy());
```
     
I tried this, but the ordering of the defintion still appears to matter as setting this after the parse is too late :)

Looking at WorkspaceParser this appears to be the default anyhow?

```
    Workspace parse(DslParserContext context, Tokens tokens) {
        // workspace [name] [description]
        // workspace extends <file|url>

        Workspace workspace = new Workspace("Name", "Description");
        workspace.getModel().setImpliedRelationshipsStrategy(new CreateImpliedRelationshipsUnlessAnyRelationshipExistsStrategy());

        if (tokens.hasMoreThan(SECOND_INDEX)) {
            throw new RuntimeException("Too many tokens, expected: " + GRAMMAR_STANDALONE + " or " + GRAMMAR_EXTENDS);
        }
```

Thanks!

**Comment by simonbrowndotje** [comment]
That's correct, the order of lines in the DSL matters, and `CreateImpliedRelationshipsUnlessAnyRelationshipExistsStrategy` is the default implied relationships strategy.

And yes, `parse()` will parse and process the DSL, so it's too late to change the implied relationship strategy after this point because the model has already been created. If you want to use your own custom strategy, I'd recommend using the new `!script` or `!plugin` features. See [this comment](https://github.com/structurizr/dsl/issues/66#issuecomment-909107884) for details.

**Comment by chrisjschultz** [comment]
Great thanks for your feedback!
