### ISSUE TITLE
Option to enforce unique relationships?

### ISSUE THREAD

**Issue by venthur** [structurizr/dsl#85]
Hi,

do you think it would be useful for a bigger round of users to add an option that enforces unique relationships? I.e. something that disallows the existence of `a -> b and a -> b` (same relation twice) and `a -> b and b -> a` (relations for both directions).

The use-case is the following: several people are modeling several softwaresystems in the same model. Each of them creating relations for their software systems. Checking all relations that have been created by the individuals for uniqueness is expensive (n × n) and error prone.

This test can be achieved already with a script that crashes whenever it encounters such relations, but an option to turn this on/off would be more convenient.

**Comment by simonbrowndotje** [comment]
I think this is best done by yourself, in a script or plugin, because everybody will want something slightly different. If I were doing this myself, I'd probably write a plugin, and use a parameter to toggle the functionality on/off.
