### ISSUE TITLE
What is the name of "this text" and how to style it?

### ISSUE THREAD

**Issue by SlytherinCz** [structurizr/dsl#86]
In my diagrams I wasn't able to style the text that appears in, for example, the enterprise boundary.

In the screenshots its the text My Software System on first, My Company second.

I couldn't find how to call that text, much less whether it has any styling options available.
I would like to style any of the text that annotates a boundary, not just the enterprise. That would be, for example a Software System boundary in a Container view.

Any help much appreciated

![Screenshot from 2021-10-11 15-01-08](https://user-images.githubusercontent.com/6987470/136794879-8de570fe-743f-49c2-bb43-38964d502628.png)

![Screenshot from 2021-10-11 15-05-57](https://user-images.githubusercontent.com/6987470/136794974-d1d38413-8702-4cc3-af0d-039ebfd96795.png)

**Comment by simonbrowndotje** [comment]
It's not currently possible to style that text I'm afraid.

**Comment by simonbrowndotje** [comment]
An update on my previous comment ... you can change the boundary styles in some limited ways (colour and an icon). See [Structurizr - Help - Notation](https://structurizr.com/help/notation#boundaries) for details.
