### ISSUE TITLE
Exclusing elements by tag not worwking in deployment views when extending

### ISSUE THREAD

**Issue by juanrferia** [structurizr/dsl#90]
Hello,
I'm facing an issue when exclusing elements by tag in deployment views if deployment environment has been extended. As a result, no elements are shown in the diagram.

To visusalize it, let's take an example from the repo: https://github.com/structurizr/dsl/blob/master/examples/ref.dsl

I'm making some change to incude a couple of tags:

```
workspace extends https://raw.githubusercontent.com/structurizr/dsl/master/examples/amazon-web-services.dsl {

    model {

        !ref "DeploymentNode://Live/Amazon Web Services" {
            tags "test"
            deploymentNode "New deployment node" {
                infrastructureNode "New infrastructure node" {
                tags "test2"
                    -> route53
                }
            }
        }

        !ref "DeploymentNode://Live/Amazon Web Services/US-East-1" {
            deploymentNode "New deployment node 1" {
                infrastructureNode "New infrastructure node 1" {
                    -> route53
                }
            }
        }

        !ref region {
            deploymentNode "New deployment node 2" {
                infrastructureNode "New infrastructure node 2" {
                    -> route53
                }
            }
        }

    }

    views {
        deployment * "Live" {
            include *
            exclude "element.tag==test"
            autolayout lr
        }
    }

}
```

As a summary, I included:
- Tag "test" for element DeploymentNode://Live/Amazon Web Services, part of the base model
- Tag "test2" for element "New deployment node", part of the extended model

Then, if the view is exclusing elements with tag "test", then diagram is empty.
I checked that, in case I try exclusing with tag "test2", then behaviour is correct.

Thanks.

**Comment by juanrferia** [comment]
I also see diagram does not show info name of deployment nodes from base model if they don't use a theme. Let me know if you prefer a separate issue for it

**Comment by juanrferia** [comment]
Some related question: I observed an Environment can only be extended by extending the Deployment Nodes within the Environment. I tried to extend the Environment itself by adding new Deployment Nodes, but that does not work. Is it an expected behaviour? Thanks

**Comment by simonbrowndotje** [comment]
At a quick glance, this looks like the correct behaviour ... you're asking the DSL to exclude elements tagged `test`, and since that's the top level deployment node, all children are also excluded.

**Comment by juanrferia** [comment]
You're right Simon. I'm facing an issue in my own model and thought I reproduce it with your example, but not the case. I'll try to reproduce it with another example. You can close and I will reopen in case I can find how to reproduce it.
Meantime, can you have a look to my other comments relalated to 1) info of deployment nodes from base and 2) extending environment itself?

**Comment by simonbrowndotje** [comment]
> You can close

Thanks, I'll close this issue ... please open separate issues for the other questions.
