### ISSUE TITLE
Using just a TAB whitespace in places in DSL files is now causing parsing errors.

### ISSUE THREAD

**Issue by tufarolo** [structurizr/dsl#94]
I had DSL that used to parse successfully in prior version of DSL (before v.16.0) but now gives an error of "unexpected tokens"
For example:  if I have this following line with only a TAB before the "=" it gives the error
(the <tab> and <space> below are indicating tab and space characters respectively)

CN_reverseProxy<tab>= container "Reverse Proxy" "Reverse Proxy Service" external

But if this same line simple adds a space before the <tab> then it parses ok. 

CN_reverseProxys<space><tab>= container "Reverse Proxy" "Reverse Proxy Service" external
[sampleWithTAB.txt](https://github.com/structurizr/dsl/files/7634277/sampleWithTAB.txt)

Unfortunately tabs are used in many places to make my DSL more readable.

**Comment by simonbrowndotje** [comment]
Can you provide a full example? (perhaps as a gist)

**Comment by tufarolo** [comment]
I added a small sample file in above post (and here
[sampleWithTAB.txt](https://github.com/structurizr/dsl/files/7634290/sampleWithTAB.txt)
)

**Comment by tufarolo** [comment]
line #9 in this sample was changed to have just a tab after the equals sign.   If that was a simple space this sample parses ok.  When a tab I get the error:   Unexpected tokens at line 9: c = softwareSystem "C"
