### ISSUE TITLE
Labels overlap and the bottom one is invisible

### ISSUE THREAD

**Issue by benbward** [structurizr/dsl#95]
Labels on intersecting relationship lines overlap and the bottom one is invisible... sometimes totally eclipsed.

I have been unable to find a way to prevent this from happening.  Am I doing something wrong or is this a bug?

```
workspace {
    model {
        user1 = person "User 1"
        user2 = person "User 2"
        softwareSystem1 = softwareSystem "Software System 1"
        softwareSystem2 = softwareSystem "Software System 2"
        user1 -> softwareSystem1 "Uses"
        user2 -> softwareSystem1 "Uses"
        user1 -> softwareSystem2 "Uses"
        user2 -> softwareSystem2 "Uses"
    }
}
```
![image](https://user-images.githubusercontent.com/1945364/145884341-1ca7728e-9911-4265-9fb1-3d19c26f3768.png)

**Comment by simonbrowndotje** [comment]
The auto-layout algorithm isn't perfect unfortunately, so you may want to use the Structurizr renderer with manual layout instead, which will allow you to move the labels (see https://structurizr.com/help/diagram-editor for details).

```
workspace {
    model {
        user1 = person "User 1"
        user2 = person "User 2"
        softwareSystem1 = softwareSystem "Software System 1"
        softwareSystem2 = softwareSystem "Software System 2"
        user1 -> softwareSystem1 "Uses"
        user2 -> softwareSystem1 "Uses"
        user1 -> softwareSystem2 "Uses"
        user2 -> softwareSystem2 "Uses"
    }
    
    views {
        systemLandscape "Landscape" {
            include *
        }
        
        theme default
    }
    
}
```

![image](https://user-images.githubusercontent.com/1009874/145952613-14d779c1-f935-46bc-a085-ede27b186bbb.png)

**Comment by benbward** [comment]
But when I remove "autolayout", it stacks all the objects on top of each other.  Is there no way to "autolayout" and then fine tune by dragging?

Further, which project houses the code that actually geography/drawings?  I'm looking but I haven't found it yet.

**Comment by simonbrowndotje** [comment]
> But when I remove "autolayout", it stacks all the objects on top of each other. Is there no way to "autolayout" and then fine tune by dragging?

Yes, you can use the auto-layout button on the toolbar; see https://structurizr.com/help/diagram-editor

> Further, which project houses the code that actually geography/drawings? I'm looking but I haven't found it yet.

Structurizr Lite/cloud service/on-premises installation are closed source, but the auto-layout library can be found on the [java-extensions repo](https://github.com/structurizr/java-extensions/tree/master/structurizr-graphviz).

**Comment by benbward** [comment]
I think part of my problem is that I'm using the VS Code extension and it does not seem to enable the "auto-layout button on the toolbar".

Thank you for your help.  By the way, I begin a new job soon and the first thing I will do when I arrive is to map out their entire enterprise using C4 and Structurizr.  I'm loving this tool.

**Comment by simonbrowndotje** [comment]
Thanks, you’re welcome. Are you using the preview feature in the VS Code extension? If so, that‘s not going to provide the full functionality of the diagram editor. I’d recommend previewing the diagrams in Structurizr Lite.

**Comment by benbward** [comment]
One last question, if I may... I'll be working in a .NET development shop.  What is your recommendation for the greatest control and flexibility in diagrams-as-code?  Would you recommend using Structurizr for .NET over the Structurizer dsl?  Or some other approach?

**Comment by simonbrowndotje** [comment]
I'd recommend the DSL for most teams, and even then you can use a combination of the DSL and the .NET library if needed:

1. Convert the DSL workspace to JSON (using the CLI)
2. Import the JSON using Structurizr for .NET
3. Run .NET code to extend the workspace

Something like this, although you'd use the CLI to convert the DSL to JSON -> https://github.com/structurizr/dsl/tree/master/docs/cookbook/dsl-and-code

**Comment by benbward** [comment]
Beautiful.  Thanks so much.
