### ISSUE TITLE
Allow to tag groups so that one can filter them out in the view description

### ISSUE THREAD

**Issue by souliane** [structurizr/dsl#98]
Hello,

There is one case in my model where to group elements together according to the DSL group keyword [1] makes my system landscape diagram very difficult to read. So I ended up commenting the grouping out. But, ideally, I would like to see the grouping for all other views, just not for this one.

Would it be possible to add a parameter so that one can disable "grouping" for a specific view? Maybe the possibility to tag groups could be added, so that one can then rely on the already existing filtering mechanism to exclude "Group"?

[1] https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#group

**Comment by simonbrowndotje** [comment]
Groups can't be disabled on a per-view basis I'm afraid, but you can exclude a whole group as follows:

```
workspace {

    model {
        g1 = group "1" {
            a = softwareSystem "A"
        }
        g2 = group "2" {
            b = softwareSystem "B"
        }
    }

    views { 
        systemLandscape {
            include *
            exclude g2
            autolayout
        }
    }
    
}
```

**Comment by souliane** [comment]
Perfect, I don't need more. Thanks!
